export const knowledgeUnits = [
  {
    "unit": "Unit 1",
    "title": "Career talks",
    "levels": [
      {
        "id": "pronunciation",
        "title": "语音知识",
        "summary": "",
        "content": [
          "单元语音知识讲解",
          "組合/ek/，/em/./8p/，/st/的发音",
          "資标",
          "发音要领",
          "发者由/#/间/k/自然滑动，舌尖接",
          "近上齿龈，气说从舌尖与齿龈间挤",
          "出，声带不振动。然后舌后部塍起",
          "/sk/接触软膊，形成阻碍，随后突然放",
          "开，让气流冲出，声带不振动。注",
          "您/s/ 向/k/过波要自然，可稍作件",
          "顿但快逃违谈。",
          "发音由/s/向/m/自然滑动，舌尖接",
          "近上齿龈，气流挤出，声带不报动。",
          "/sm/",
          "然后双唇闭合，舌身自然平伸，气流",
          "从鼻腔送出，声带报动。",
          "/sp/",
          "发音由/s/向/P/自然滑动，舌尖接",
          "近上齿龈，气流挤出，声带不报动。",
          "然后双唇紧闭，阻碍气流，最后双唇",
          "突然放开，使气流冲出成音，声带不",
          "振动，发音时/s/到/p/过渡紧读，在",
          "词首时，/p/常因浊化规则读成/b/。",
          "/st/",
          "发音由/s/向/t/自然滑动，舌尖接",
          "近上齿龈，气流挤出，声带不振动。",
          "然后舌尖抵住上齿龈，形成阻碍，最",
          "后舌尖突然放开，使气流冲出成音，",
          "声带不振动，在词首时，/t/往往会",
          "浊化为/d/。",
          "图解",
          "常见字母组合",
          "示例",
          "sk",
          "skate,skil.",
          "sirt",
          "Sm",
          "smile, smell，",
          "small",
          "sP",
          "SPort, speak，",
          "spPecial",
          "st",
          "story, still，",
          "student",
          "（二）"
        ]
      },
      {
        "id": "basics",
        "title": "基础知识",
        "summary": "",
        "content": [
          "单元基础知识背记",
          "&重点单词",
          "•名词",
          "1. 市场 n.market",
          "2.公司 n.company",
          "3.汗，汗水 n.sweat",
          "4.（液体的）滴n,drop",
          "5.西瓜 n.watermelon",
          "6.职业；事业 n.career",
          "7.刷子；毛刷 n.brush",
          "8.面试，面谈 n.interview",
          "9.演说，演讲 n.speech",
          "10.上下文，语境 n.context",
          "11.技能，技巧，技艺 n.skill",
          "12.“蜘蛛人”（指高空作业人员）n.spiderman",
          "13.（飞机或宇宙飞船上的）驾驶员，飞行员 n.pilot",
          "动词",
          "1.需要 v.require",
          "2.组织、策划、安排 v.organise",
          "3. 取代 、replace",
          "4. 提供，供应，供给 v.provide",
          "5.使想起v.remind",
          "•形容词",
          "1.新生的adj.newborn",
          "2.虚拟的，模拟的 adj.virtual",
          "3.湿的，潮的，潮湿的adj. wet",
          "4.（数量、水平或价值）少的，低的 adj.low",
          "副词",
          "在更远处；往更远处 adu.beyond",
          "•词形变换",
          "1.现款：现金 11.cash-出纳员 n. ceshier"
        ]
      },
      {
        "id": "phrases",
        "title": "重点短语",
        "summary": "",
        "content": [
          "重点短语",
          "1.因为 because of",
          "2. 将⋯⋯切成 cut into",
          "3. *⋯⋯付钱 pay for",
          "4.报名 sign up for",
          "5.汗滴 drops of sweat",
          "6. 突然出现 spring up",
          "7.请假 take the day off",
          "8. 捕鼠人 mouse catcher",
          "9.对某人微笑 smile at sb.",
          "10. 保持不变 stay the same",
          "11.化为乌有 go up in smoke",
          "12. 靠某人自己 on one‘s own",
          "13.被⋯•⋯所取代 be replaced by",
          "14.充满；装满 be filled with"
        ]
      },
      {
        "id": "sentences",
        "title": "重点句型",
        "summary": "",
        "content": [
          "重点句型",
          "1.很高兴在我工作的最后一天见到你。",
          "It's so nice to see you on my last day at work.",
          "2. 过去的30年充满了挑战和欢乐。",
          "The past 30 years were fillcd with both challenges and joys.",
          "3.所有高空中的岁月，都将珍威在我的记忆里。",
          "All my days up high in the air will be kept i my memory•",
          "4.擦窗户并不总被认为是份好卷事，但我水远不会后悔。",
          "Window cleaning is not always considered a good job,but T'll never regret it.",
          "2.人；个人1.person~-个性，性格 n.personnlity",
          "3.李观：游览 n,tour旅游业，观光业.n,tourism",
          "4.确信的；有把握的 adj.sure-• 确实地，无疑地",
          "adv.surely",
          "5. 时尚 7.fashion 一时髦的，流行的 adj.fashionable",
          "6. 领导者 n. leader 一领导才館，領导素质 n. lendership",
          "7.实际存在的，真实的adj.real -真实，现实1.",
          "reality",
          "8. 交流，沟通v.communicate一信息；交流，沟通",
          "communication",
          "9.挑战，具有挑成性的事物 n.challenge--富于挑战",
          "性的；困难而有趣的 adj. challenging",
          "10.必要的，必需的，必不可少的 adj.necessary （反",
          "义词）不需要的，不必要的；多氽的 adj.",
          "unnecessary",
          "15.时尚设计师 fashion designer",
          "16.被认 是⋯••be considered sth.",
          "17.还浙地，一点一点地 bit by bit",
          "18. 太空旅行导游 space tour guide",
          "19. 带领某人到菜地 lead sb. to sp.",
          "20. 重要的事情 important matters",
          "21.维持••••的运转 keep sth.running",
          "22. 某人记得某事 keep sth. in one's memory",
          "23. 一种成就感 a sense of achievement",
          "24. 在虛拟现实环境中 in virtual reality",
          "25.使某人想起某事 remind sb.of sth.",
          "26. 产生影响；引起变化 make a difference",
          "27.兴起；正在成为趋势 on the way",
          "WYA 背记本",
          "5.城市因为我们变得更加明亮，而这份工作也会让我们大显身手。",
          "The city shines brigbter because of us,and the job will make us shine,too.",
          "6.如果你生活在14 世纪中期，你可能已经成为了一名捕鼠者。",
          "II you lived in the mid-1300s,you might have been e mouse catcher.",
          "7.现在，科技甚至正以更快的速度发展中。",
          "Now,technology is developing et an even faster speecd.",
          "8.哪些职业将走向消亡，哪些又将应运而生？",
          "Which jobs will soon be history, and which ones are on Lhe way？",
          "9.一些传统职业正逐渐谈出视野。然而，新的职业正在涌现出来，以满足新的需求。",
          "Some traditional jobs are disappearing. However, new ones are springing up Io meet new needs.",
          "10.我们不能只是坐在办公桌前，期望事情保持不变。",
          "We can't just sit at our desks and expect things te stay the same.",
          "11. 在未来，太空旅行肯定会以更低的成本被提供。",
          "In the future, Lravelling to space will surely be provided at a lower cost.",
          "12. 随着新技术的发展，未来可能不再需要人类飞行员了！",
          "Wich the development of new technology,there might be no need for human pilots in the future！",
          "（三）"
        ]
      },
      {
        "id": "writing",
        "title": "话题范文",
        "summary": "",
        "content": [
          "单元话题范文背记",
          "A",
          "无人机飞行员、数据工程师、机器人散练、太空厨师••⋯在人工智能 AI（Artificial Intelligence） 高速发展",
          "的今天，这些曾经闻所未闻的职业正在逐步走人大众视野。假如你是李华，请你向某英语报“Future Life”栏目",
          "投稿，写一篇80词左右的邮件，谈谈你对未来职业的看法。内容包括：",
          "1.对于人们未来职业的预测，如工作类型、方式、地点及时长等；",
          "2. 未来职业变化带来的影响；",
          "3.中学生适应未来职业应做的准备，如健康生活方式、个人提升、人际关系等。",
          "Dear Editor，",
          "With the rapid development of Artificial Intelligence, many new jobs have appeared, such as drone pilots，",
          "data engineers, robot coaches,and space chefs.",
          "I believe that in the future, people will only need to work at home for one hour a day,because other work",
          "will be done by robots. We will have more time to travel to relax ourselves. We will also have more time to",
          "spend with our family. To meet these challenges in the future, we should now actively exercise our bodies and",
          "work hard to learn knowledge of Al. At the same time, we should improve our relationship with our family and",
          "friends.",
          "Yours，",
          "Li Hua",
          "B",
          "科技正以前所未有的势头重塑人类的就业方式。某英文公众号正在开展以“我的未来职业”为主题的征文",
          "活动。请你写一篇短文，介绍你未来的理想职业。词数 80 左右，可适当发挥。",
          "提示问题：",
          "•What do you want to be in the future？",
          "•What will the job be like in the future？",
          "• Why do you want to choose the job？",
          "WYA下• 记本",
          "I want to be a teacher in the future. As technology will change how we work,teaching will connect",
          "trnditions with modern tools. In the future,teachers will give lessons with the help of Al robots and use virtual",
          "reality to bring lessons to life. Moreover,teachers can check students' progress through technology in order to",
          "give them specific suggestions on their study.",
          "There are two reasons for me to be a teacher. First,I love children and teaching brings me a strong sense of",
          "achievement, Second,I got a lot of help from my teacher and I'd like to be a great person like her. I'm excited to",
          "use technology in teaching and guide students to a better future.",
          "（四）"
        ]
      },
      {
        "id": "points",
        "title": "重要考点",
        "summary": "",
        "content": [
          "单元重要考点背记",
          "考点",
          "drop 的用法",
          "作名词",
          "drop的用法",
          "作动词",
          "意为“滴；少量”，为可数名词。如：Add a drop oflemon juice to the drink.",
          "在伙料里加一滴柠檬汁。",
          "（1）意为“降低：减少\"。如：They dropped the price ofthe dress.他们降低",
          "了裙子的价格。",
          "（2）意为“掉落；落下\"。如：The apple dropped from the tree. 苹果从树上掉",
          "了下来。",
          "（3）意为“放下；使落下”。如：Drop your bagshere.把你的包放在这儿。",
          "（4）意力“放弃；停止”。如：I dropped the habit ofsmoking. 我戒掉了吸烟",
          "的习惯。",
          "考点",
          "remind 的用法",
          "remind 作动词，意为“提醒；使想起”。常见用法有：",
          "remind sb.of sth.使某人想起某事",
          "remind 的用法",
          "remind sb. （not） to do sth. 提醒某人（不要）做某事",
          "remind sb.+ that 从句 提醒某人⋯",
          "如：",
          "The movie reminds me of my childhood.这部电影让我想起了我的童年。",
          "My parents often remind me to study hard. 我父母常常提醒我努力学习。",
          "My sister wants to remind me that tomorrow is her birthday. 我姐姐想提醒我明天是她的生日。",
          "考点",
          "challenging 及相关词的用法",
          "考点",
          "词性及含义",
          "challenging",
          "作形容词，意为“富于挑战性的；",
          "困难而有趣的”",
          "作名词，意为“挑战；难题；质疑”",
          "challenge",
          "作动词，意为“挑战；质疑；考验”",
          "示例",
          "Running a marathon is really challenging for",
          "beginners.跑马拉松对初学者来说真的很有挑战性。",
          "Learning a new language is a big challenge. 学一门新",
          "语盲是个很大的挑战。",
          "The teacher challenged the students to solve the",
          "problem.老师让学生们解决这个问题来考验他们。",
          "WY 八下• 记本",
          "requlre 的用法",
          "ruuire 作动，意为“需婴，要求”，其后可接名词或代词。",
          "require sth.循要基物",
          "require sb. to do sth.婴求某人做基亦",
          "require的用法",
          "require doing 需要做某事（主语通常是物）",
          "require +that从句 需要⋯•（从句中常用should+动词原形，should可省略）",
          "如：",
          "Baking a cake requires flour, eBgS,and sugar.烤蛋糕需要面粉、鸡蛋和糖。",
          "The teacher requires students to hand in the homework on time. 老师要求学生按时交作业。",
          "The house requires cleaning belore guests arrive.房子在客人来之前需要打扫。",
          "The school requires that students （should）wear uniforms.学校要求学生穿校服。",
          "考点",
          "provide 的用法",
          "provide作动词，意“提供；供给”。常见用法有：provide sth. 提供某物，provide sth. for sb. /provide sb.with",
          "sth.为某人提供某物。如：",
          "The museum provides guided tours every hour.博物馆每小时提供导游服务。",
          "The school provides breakfast for students every morning.学校每天早上为学生提供早餐。",
          "考点",
          "beyond 的用法",
          "意为“在更远处；向更远处\"表示位置",
          "作副词",
          "beyond的用法",
          "作介词",
          "意为“在/向……较远的一边；超出（范围），表示空间",
          "意为“迟于；超过（某个时间点）\"，表示时间",
          "意为“超出⋯•之上；除⋯⋯之外”，表示程度",
          "如：",
          "She looked beyond,trying to see the ocean.如望向远方，试图看见大海。",
          "The house is beyond that hill. 房子在那座山的另一边。",
          "Don't stay out beyond 11 pm. 不要在外面待到晚上11点以后。",
          "Her talents go beyond singing.她的才能不止于唱歌。",
          "考点",
          "low 的用法",
          "1ow的用法",
          "Thc price of these books is low for poor students to buy.",
          "作形容词时，可意为“（数量、",
          "水平或价值）少的，低的”",
          "这些书价格低廉，贫困学生也能买得起。",
          "Can you turn the music lower? You'll wake the baby.",
          "能把音乐放小声点吗？你要把孩子吵醒了。",
          "作副词时，可意为“低声地”",
          "His grades were a low, but he worked hard to improve them quickly.",
          "作名词时，可意为“低水平；低谷”，",
          "他的成绩曾处于低谷，但他努力后很快就提升了。",
          "常用短语：at a low 处于低谷"
        ]
      }
    ]
  },
  {
    "unit": "Unit 2",
    "title": "Growing pains and gains",
    "levels": [
      {
        "id": "pronunciation",
        "title": "语音知识",
        "summary": "",
        "content": [
          "单元语音知识讲解",
          "辅音组合/str/，/spr/，/skr/的发音",
          "音标",
          "发音要领",
          "发音时，先发/s/音（舌尖轻触上齿",
          "龈，气流席擦，声带不振动），快速",
          "接/t/音（舌尖抵上齿龈，阻碍气流",
          "后突然放开送气，声带不振动），再",
          "/str/ 过渡到//音（舌尖卷起近上齿龈",
          "后部，声带振动，气流摩擦）；/t/音",
          "在词首常浊化为/d/音，实际发音",
          "趋近/sdr/，但音标仍标/str/，发音",
          "时三个音素紧密连续。",
          "发音时，起始发/s/音（舌尖轻触上",
          "齿龈，气流庠擦，声带不振动），快",
          "速衔接/P/音（双唇紧闭阻码气流，",
          "然后突然放开送气，声带不振动），",
          "随即过疲到//音（舌尖卷起近上",
          "/spr/",
          "齿龈后部，声带振动，气流摩擦）：/",
          "s/音到/p/音爆破感稍弱、衔接",
          "快，/P/音在词首常因浊化规则使",
          "得实际发音趋近/b/音，整体发音",
          "版滑紧凑。",
          "发音时，先发/s/音（舌尖轻触上齿",
          "龈，气流摩擦，声带不振动），快速",
          "过渡到/k/音（舌后部贴软腭，气流",
          "爆破，声带不振动），紧接着发/5/",
          "/skr/",
          "音（舌尖卷起接近上齿龈后部，声",
          "带振动，气流摩擦）；整体发音紧",
          "凑，/s/音向/k/音过渡时不停顿，",
          "口语中//音偶有轻微浊化倾向。",
          "图解",
          "常见字母组合",
          "示例",
          "str",
          "Strange，",
          "street，",
          "Strong",
          "spr",
          "SPrIng，",
          "EPread，",
          "SpTay",
          "SCI",
          "screen，",
          "scream，",
          "describe",
          "（二）"
        ]
      },
      {
        "id": "basics",
        "title": "基础知识",
        "summary": "",
        "content": [
          "单元基础知识背记",
          "）重点单词",
          "•名词",
          "1.灯7.lamp",
          "2.情节 7. plot",
          "3.腕（关节）n.wrist",
          "4.长沙发 n. sofa",
          "5.学期 7.term",
          "6. 同龄人 7. peer",
          "7.看法，态度 7. attitude",
          "8. 童年，儿童时代 n.childhood",
          "9. 女士宽松短衫，女衬衫 n. blouse",
          "10.谈话，交谈，会话 n.conversation",
          "11.下午（用于表示钟点的数字之后）n.pm",
          "WY八下 背记本",
          "12. 要点、点，中心意思，主要會义，观点 n.point",
          "1.花（时间）t.spend",
          "2.失败，米做到v.Fnil",
          "3.系I绑。贴v.attach",
          "4.打断（••的）讲话，中断（……的）行动，打扰v.",
          "interrupt",
          "形容词",
          "1.苍白的 adji.pale",
          "2. 懒洋洋的，擁懒的 adj.lazy",
          "3.使人心碎的 adj.hcartbrcaking",
          "4.年老的，渐老的（委婉用法）adj. cldcrly",
          "副词",
          "（在）今晚 adv. tonight",
          "介词",
          "在•⋯上面 prep. upon"
        ]
      },
      {
        "id": "phrases",
        "title": "重点短语",
        "summary": "",
        "content": [
          "重点短语",
          "1. 拒绝 turn down",
          "2. 往回走 head back",
          "3.适应；融人 fit in",
          "4.拾起；捡起 pick up",
          "5.想到；想起 think of",
          "6.切断；切除 cut off",
          "7.爱上⋯…•fall in love with",
          "8. 未能做到⋯•fail to do sth.",
          "9.被排挤在外 be left out",
          "10.参加⋯•⋯的选拔 try out for",
          "11.非常重要的事 a big deal",
          "12. ⋯⋯感到骄傲 be proud of",
          "13.上气不接下气 out of breath",
          "14. 同龄人的压力 peer pressure",
          "15.突然发生在某火/某物身上，降临到某人/某物身"
        ]
      },
      {
        "id": "sentences",
        "title": "重点句型",
        "summary": "",
        "content": [
          "重点句型",
          "1.说话算话！",
          "A deal is a dea！！",
          "2.对不起，我对你发脾气了。",
          "I'm sorry for being cross with you.",
          "3.成长从来都不是一件容易的事。",
          "Growing JP will never be an easy thing.",
          "4.为什么这么久才拿到你的手机？",
          "Why did is take that long ! get your phone？",
          "•其他",
          "保证.承，诺盲 许诺，保证，答应 w. promise",
          "调形变换",
          "1.滑雪v.ski--滑雪运动1.skiing",
          "2. 女警察1.policewoman-~（复数）policewomen",
          "3.清楚的，明白的adj. clear--清楚地，明白地 adv.",
          "Clearly",
          "4. 按；压w. press --（工作或生活中的）压力n.",
          "pressure",
          "5.完鳖的，彻底的 adj.",
          "完成 v.complete--完全地，",
          "全地，彻底地 adu. completely",
          "6.同意 v.agree--同意；协议 n.agreement --意见不",
          "和，分歧，爭论 n.disagreement",
          "7.使失望 v. disappoint 一失望的，沮丧的（形容人）",
          "adj. disappointed-令人失望的，沮丧的（形容物）",
          "adj.disappointing",
          "上 fall upon sb. /sth.",
          "16. 守信，遵守诺言 keep one's promise",
          "17. 许诺做某事 promise to do sth.",
          "18. 在外面待到很晚 stay out late",
          "19.对•••生气或不满 be cross with sb.",
          "20. 与••保持联系 stay in touch with",
          "21.被吸引走；分心 be drawn away",
          "22. 对⋯…失望 be disappointed at",
          "23.发生变化，产生转变 take a turn",
          "24.从痛苦到收获 from pain to gain",
          "25. 忍不住做某事，不能停止做某事 can't help",
          "（doing） sth.",
          "26. 与某人意见不合 have a disagreement with sb.",
          "27.使某人不再去想（担忧）某事 take sb. 's mind off",
          "sth.",
          "5.在生活的任何阶段，都可能发生在我们身上。",
          "It may fall upon us at any stage in our lives.",
          "6.但很快，我彻底爱上了这项运动。",
          "But soon, I fell completely in Love with the sport.",
          "7.起初，我只是为了转移注意力才游冰的。",
          "At first, I swam just 1e take my mind off things.",
          "8. 当时那些伤心欲绝的文字让我忍俊不禁。",
          "I couldn't help laughing at my heartbreaking words then.",
          "9.恐怕你花在手机上的时间太多了。",
          "I'm afraid that too much of your time is spent on your phone.",
          "10.我一直陪着她，直到她被女警察带回家。",
          "I waited with her until she was taken home by e policewoman.",
          "11.没有遵守承诺，所以你下次不能在外面待到很晚了。",
          "The promise wasn't kept,so you can't stay out late next time.",
          "12. 回顾过去，用全新的眼光看待我的痛苦和收获，真是太好了",
          "I's great ne look back and see my pains and gains with fresh eyes.",
          "13.那时候，我因为个子太矮没能人选篮球队而无比失望。",
          "Back then, I was so disappointed at being too short and failing 10 get on the basketball team.",
          "（三）"
        ]
      },
      {
        "id": "writing",
        "title": "话题范文",
        "summary": "",
        "content": [
          "单元话题范文背记",
          "A",
          "初中生活中，那些让你成长的珍贵时刻是否仍历历在目？你校英语报正开展以“My growth”为题的征文",
          "活动，请你写一篇80词左右的短文，讲述最触动你的一段成长经历：或许是一次突破，一份友谊，一个启发，或",
          "是一份责任。",
          "内容提示：",
          "1. What does growth mean to you？",
          "2. What was your experience about growth？",
          "3. How did this experience influence you？",
          "My growth",
          "Growth, to me, means becoming more confident.",
          "During my junior high school years, the most touching growth experience was when I joined the school",
          "speech competition. At first, I was very nervous and short of confidence. But as I prepared for the competition，",
          "I read a lot and practised speaking day after day. When I finally stood on the stage, I pushed myself to express",
          "ideas clearly.",
          "This experience has greatly influenced me. I've become more confident in expressing myself and learnt to",
          "stay calm under pressure. I know that as long as I keep on,I can overcome any challenges in the future.",
          "B",
          "作为中学生，我们在学习和生活中不可避免地会退到很多问题，那么应该如何面对并解决这些问题呢？假",
          "设你校英文报“Growth”专栏近期正在开展以“成长的烦恼（Growing pains）”为话题的征文活动，请你根据以下",
          "提示，写一篇英语文章投稻。词数80左右，可适当发挥。",
          "内容提示：",
          "1. What was your main teenage problem？",
          "2. How did you deal with it？",
          "3. What have you learnt from the experience？",
          "WYA下•胃记本",
          "Recently our class has talked about \"Growing pains” of teenagers. 1 once had a problem that 1 was a hri",
          "shy and had trouble making friends.",
          "Once，there was a group project in class. I was really nervous about working with others. But 1 knew Itd",
          "to face it. I took a deep breath and started to communicate with my classmates. 1 listened carefully to their idens",
          "and shared my own thoughts,too. Slowly,I became more confident and we completed the project successfuly.",
          "From this experience,I learnt that we should be brave to take the first step. When we face difficulties,re",
          "should try to overcome them instead of running away from them. Only in this way can we grow up and become better.",
          "（四）"
        ]
      },
      {
        "id": "points",
        "title": "重要考点",
        "summary": "",
        "content": [
          "单元重要考点背记",
          "promise 的用法",
          "作动词，意为",
          "“承诺；许诺”",
          "promise",
          "的用法",
          "作名词，意为",
          "“承诺；诺言”",
          "promise sb.sth.=promise sth.to sb.向某人许诺某物",
          "promise to do sth.承诺做某事",
          "promise+从句 许诺⋯•",
          "make a promise 许下诺言",
          "break a promise 违背承诺",
          "keep apromise 信守承诺",
          "看点",
          "realise 的用法",
          "realise 作动词，常见用法如下：",
          "（1）意为“理解；意识到”，如：",
          "She realised she left her keys at home.她意识到她把钥匙落在了家里。",
          "（2）意为“实现；达成”，通常指使梦想、计划、目标等成为现实。此时 realise 可与 come true 互换，但 come true",
          "后面不接宾语，主语通常是“梦想/愿望”本身。如：",
          "She finally realised her dream of becoming a doctor. = Her dream of becoming a doctor finally came true.她終",
          "于实现了成为医生的梦想。",
          "考点《",
          "point 的用法",
          "（1）意为“要点，重点；中心意思，主要含义；观点”。如：The main point ofher",
          "speech was environmental protection.她演讲的要点是环境保护。",
          "作名词",
          "（2）意为“得分；分数”。如：She got 95 points on the test. 她考试得了95分。",
          "point的用法",
          "作动词",
          "（1）意“指向；指着\"。如：He pointed at the map and told us where the hotel",
          "was.他指着地图告诉我们宾馆在哪里。",
          "（2） 意为“强调；指出”。如：She pointed out that we were running out oftime.",
          "她指出我们快没时间了。",
          "考点",
          "disappointed 及相关词的用法",
          "考点",
          "disappoint",
          "disappointed",
          "词性、含义及用法",
          "作动词，意为“使失望”。常见用法：",
          "disappoint sb. 使菜人失望，相当于 let",
          "sb.down/make sb. disappointed",
          "作形容词，意为“失望的”，通常修",
          "饰人",
          "示例",
          "I hate to disappoint you, but I'm really not interested.",
          "我不想使你扫兴，但我确实不感兴趣。",
          "The children were disappointed that it rained on their",
          "picnic day.孩子们因为野餐当天下雨而感到失望。",
          "WY八下，背记*",
          "续表",
          "考点",
          "词性、含义及用法",
          "作形容词，恋为“令人失望的”，通怡",
          "disappointing",
          "修饰事或物",
          "示例",
          "The movie turned out to be really disappointing. 这部",
          "电影结果真的很令人失望。",
          "点5",
          "fall 的用法",
          "fail in （doing）sth.做某事失敗了",
          "作动词，意为“失败；未能做到”",
          "fail to do sth.未能做某班",
          "fail的用法",
          "作动词，意为“不及格”",
          "1 fail （in） the exam 考试不及格",
          "如：",
          "He failed （in） his driving test.他驾驶执照考试不及格。",
          "He has never failed in keeping his promises. 他从未食言过。",
          "She failed to get into art college.她未能进入艺术学院。",
          "考点",
          "completely 及相关词的用法",
          "考点",
          "completely",
          "complete",
          "词性、含义及用法",
          "作副词，意为“完全地；彻底地；",
          "全部地”",
          "作形容词，意为“完整的；全部",
          "的；完成的”",
          "作动词，意为“完成；使完整；",
          "结束”",
          "示例",
          "She completely cleaned her room.她彻底打扫了房间。",
          "The set of books is complete. 这套书是完整的。",
          "We need to complete this form before Friday. 我们需",
          "要在周五前填完这张表格。",
          "……"
        ]
      }
    ]
  },
  {
    "unit": "Unit 3",
    "title": "What makes a great team？",
    "levels": [
      {
        "id": "pronunciation",
        "title": "语音知识",
        "summary": "",
        "content": [
          "单元语音知识讲解",
          "田解",
          "常见宇母组合",
          "/kw/",
          "发音要领",
          "发音时，由/K/音滑向/W/音。舌",
          "后部先隆起，紧貼软脬后抬向软",
          "腰，口形由开至圆，双雇逐浙收团",
          "并前凸，声带振动，发音短促。",
          "qu",
          "示例",
          "gueen,yality，",
          "question",
          "（二）"
        ]
      },
      {
        "id": "basics",
        "title": "基础知识",
        "summary": "",
        "content": [
          "单元基础知识背记",
          "③重点单词",
          "•名词",
          "1.帐篴 n.tent",
          "2.角色 n.role",
          "3. 戏剧n.drama",
          "4. 努力1.effort",
          "5.梯子 n.ladder",
          "6. 顶，顶部 11.roof",
          "7. 队友 n. teammate",
          "8. 正午，中午 n.noon",
          "9.队长，组长 n.captain",
          "10. 合作，协作 n.cooperation",
          "11.登山运动n.mountaineering",
          "12.细，粗纲，绳紫 n.rope",
          "13.优点，长处，优势 n.strength",
          "14. 合作，协作，配合n.teamwork",
          "15. 基地，根据地，总部，大本替 n. base",
          "16.胶带，胶布 n.tape",
          "•动词",
          "1.投票，表决 t.vote",
          "2.突然停止；呆住v.freeze",
          "3.扎营，宿营，露营 v.camp",
          "•形容词",
          "1.志愿的 adj.voluntary",
          "2.糟糕的，恶劣的adj.awful"
        ]
      },
      {
        "id": "phrases",
        "title": "重点短语",
        "summary": "",
        "content": [
          "重点短语",
          "1.分发，分配 give out",
          "2.处理 deal with",
          "1",
          "3.北方的，北部的； 北的adj. north",
          "4. 益怯的，腼腆的（尤指在陌生人而前）adj. shy",
          "词形变换",
          "1. 管理，监督；指导 v.direct-导演 n.director",
          "2. 带路，领路；引领v.lead--领导者 1.leader",
          "3. 不作声的adj. silent-沉狀，缄映 n, silerice",
          "4.见到，過到v.meet--会议，集会 1.meeting",
          "5. 暗示，暗指 v.suggest-建议，提议 n. suggestion",
          "6. 意见，建议；忠告，劝告 7.advice--建议 v. advise",
          "7.虚弱的；无力的adj.weak一弱点，点，不足1.",
          "weakness",
          "8. 有信心的，自信的adj. confident--自信，信心1。",
          "confidence",
          "9.（肉体上的）疼，痛7.pain-令人痛苦的 adj.",
          "painful",
          "10.爬（山），登（山）w.climb- 登山运动员n.climber",
          "11.（数量、水平或价值）少的，低的adj. low 把（某",
          "物）移低，降下 w.lower",
          "12.使破裂，使破碎 c. break--坏的，破碎的；断裂的",
          "adj.broken",
          "13.你（主格）pron. you -你（宾格）pron. you一-你的",
          "（形容词性物主代词）prom. your-你的（名词性",
          "物主代词）pron.yours",
          "3.同意，接受（某人的看法或计划）BO with sb. /sth.",
          "4. 确保 make sure",
          "5. 而且 what's morc",
          "6.投票支持 vote lor",
          "7.感觉像是 fcel like",
          "8. 解决，算出 work out",
          "9.发现，查明 find out",
          "10. 愤然离开 storm off",
          "11.做决定 make decisions",
          "12.必须，不得不 have to",
          "13. 小组成员 team member",
          "14.做出选择 make a choice",
          "15. 愿意做 be willing to",
          "16. 团队合作 work as a team",
          "17. 一点儿；有一点儿abit",
          "18. 提出建议 make suggestions",
          "19.（登山）大本营 base camp",
          "20.做志愿工作 do voluntary work",
          "21.尽一切努力 make every effort",
          "22. 世界屋脊 roof of the world",
          "23. 抯心，忧虑，关注 worry about",
          "24. 以⋯⋯为例 take..as an example",
          "25. 拿走，带走，使消失 take sb./sth. away",
          "26. 独立地，自己一个人地 on one's own",
          "27.（尤指到山上或森林里）去露 g0 camping",
          "28. 在（某人）伸手可及的地方 within reach （of sb.）"
        ]
      },
      {
        "id": "sentences",
        "title": "重点句型",
        "summary": "",
        "content": [
          "重点句型）",
          "1.这对我来说是莫大的荣幸。",
          "It is a great honour for me.",
          "2. 如果我伤害了丽莎的感情怎么办？",
          "What il 1 hurt Lisa's feelings？",
          "3.然而，刘（连满）已经筋疲力竭，无法继续前进。",
          "But Liu was too tired to keep going.",
          "4.首先，你应该和丽莎讨论一下这件事。",
          "First,you should discuss the matter with Lisa.",
          "5. 队员们虽然担心他，但他们必须继续攀登。",
          "The team were worried,but they had 1e carry on.",
          "6.每个人都看着我，希望我能做出决定。",
          "Everyone looked at me and expected me to decide.",
          "7.我们是一个团队，他应该随时向我们求助。",
          "We're a team. He should feel free 1 turn t0 us.",
          "8，那么，为什么不让丽莎和玛丽同时尝试两个角色呢？",
          "Then, why not have Lisa and Mary both try two roles？",
          "9.感谢您让我成为我们的戏剧《白雪公主》的导演。",
          "Thank you for making me director of our drama,Snow White.",
          "10.所以，出现分歧时，领导者应该承担起责任。",
          "So the leader should take responsibility in times of disagreement.",
          "11.团队中有些人认为玛丽更合适。其他人则支持丽莎。",
          "Some of the team thought Mary was better. The others went with Lisa.",
          "12.他做得很好，不必对自己太苛刻。",
          "He has done a good job,and he doesn't have Le be too hard on himself.",
          "13. 无氧攀登极其危险，但他们深知刘（连满）更需要氧气支持。",
          "I was dangerous t climb without oxygen, but they knew Liu needed it.",
          "14.他虽未登顶，却用自己的力量托起整个团队，让他们的壮举 人中国登山史册。",
          "He did not reach the top, but he shouldered his team into China's mountaineering history.",
          "WYAT•資记* 12",
          "（三）"
        ]
      },
      {
        "id": "writing",
        "title": "话题范文",
        "summary": "",
        "content": [
          "单元话题范文背记",
          "A",
          "作为一名中学生，我们不仅要有独立意识，还要有团队合作意识。在团队合作中，我们能互相学习，互相帮",
          "助，共同讨论，我们还能分享学习中的快乐与悲伤，能感受到爱与被爱。让团队合作精神伴随我们成长！请你",
          "以“How to learn together es a team？”为主题写一篇英语演讲稿，代表学校参加中学生英语讲比赛。词数80",
          "左右。",
          "Good morning,ladies and gentlemen. Today my topic is \"How to learn together as a team？\".",
          "Teamwork is always very important. It offers us chances to learn how to get along well with others and to",
          "share our experiences with others. We can learn from each other and help each other. But how could we learn",
          "together as a team？",
          "In my opinion,we should be friendly to each other. When others have problems, we should offer help to",
          "them. Maybe we don't know how to do them, but we can discuss together and find a way to solve them at last.",
          "After all, when I work together with others,I may be able to learn from them. Meanwhile, working together",
          "with others helps us grow up. Many hands make light work. We need teamwork in our daily life.",
          "That's all for my speech. Thank you！",
          "B",
          "众人拾柴火焰高。在学习和生活中，大家一起团结协作，往往能取得更好的成果。你校英文专刊以“Mang",
          "hands make light work”为题，在八年级开展征文活动，请你结合你的一次团队合作经历，用英语写一篇短文投",
          "稿，谈一谈你对团队合作的看法和感悟。词数80左右。",
          "Many hands make light work",
          "Have you heard of the saying “Many hands make light work”？ I'd like to share one of my experiences with",
          "you. It makes me understand it better.",
          "Last month, our teacher asked",
          "us to make a book report on a book called Treasure Island. Our team",
          "members decided to work together to do the task. I like reading novels and always have a better understanding",
          "of the roles,so I offered to pick out",
          "the exciting parts of the novel. My friend Amy searched for some",
          "information about the writer while other members read some reviews online. We also asked our teacher for",
          "advice. Through the teamwork, the report got great success. We were all very happy.",
          "From this experience, I believe that working together not only brings us happiness but also leads us to",
          "succesS.",
          "（四）"
        ]
      },
      {
        "id": "points",
        "title": "重要考点",
        "summary": "",
        "content": [
          "单元重要考点背记",
          "考点《",
          "director 的用法",
          "director 作名词，意为“导演”，由“direct（v.指导，管理）+-or（名词后缀）”构成。如：",
          "At last, when the filming was done,the director was really pleased. 最后，当电影拍摄完成时，导演十分消意。",
          "【拓展】（1）director 作名词时，还可意为“部门负责人”。如：",
          "Fe started as an office junior and then became a director. 他开始是一名办公室初级职员，后来成了主管。",
          "（2）后级-or 常加在某些动词后，构成名词，表示“⋯⋯的人（或物）”。如：",
          "act（w.表演） actor（n.演员）",
          "visit（v.参观）--visitor（n.游客）",
          "invent（v.发明） -inventor（n.发明者）",
          "collect（v. 收藏）--collector（n. 收藏家；收集者）",
          "WY 下 背 本",
          "give out 的用法",
          "give out 意 “分发，微发”，是“动词＋词”型短语。当其后所接的宾语为名词时，名问放在 give oul 之间或",
          "out之后均可；当所接的宾语为代词时，代词要放在give 与out 之间。如：",
          "The teacher is giving out books to the class. 老师正在给全班同学发书。",
          "Can you give them out.please？请你把它们分发出去好吗？",
          "【拓展】give out 的其他常见用法如下：",
          "含义",
          "发出（光、热）",
          "耗尽；用尽",
          "示例",
          "The sun gives out light and heat to the.earth. 太阳给了地球光和热。",
          "After two hours,her patience gave out. 两小时后，她失去了耐心。",
          "音点",
          "考点",
          "silence 与 silent 辦析",
          "silence",
          "词性、含义及用法",
          "作名词，意为“沉歌；寂静”，是不可数",
          "名词。常用搭配：in silence 安静地；",
          "break the silence 打破沉默",
          "示例",
          "They walked on in silence for a while. 他们默默地维续走了",
          "silent",
          "作形容词，意为“沉歌的；寂静的”，在",
          "句中作表语或定语。常用搭配：",
          "remain/stay/keep silent 保持沉默",
          "一会儿。",
          "A knock on the door broke the silence. 敲门声打破了寂静。",
          "I don't like the silent hours of the night. 我不喜欢晚上寂静",
          "的时间。",
          "Please look at the sign. It says “Keep silent”.请看告示牌。",
          "上面写着“保持安静”。",
          "考点",
          "advise 的用法",
          "advise sb.to do sth.建议某人做某事",
          "advise sb. not to do sth.=advise sb.against doing sth.建议某人不要做某事",
          "advise的用法",
          "advise doing sth.建议做某事",
          "advise + that从句建议⋯••（从句中调语谐用“should+动词原形”，should可省略）",
          "如：",
          "The doctor advises her to take more exercise. 医生建议她多锻炼。",
          "She advises him not to play computer games too late. = She advises him against playing computer games too",
          "late.她建议他别玩电脑游戏太晚。",
          "My parents advise going to bed early on school nights.我父母建议上学日晚上早点睡觉。",
          "The teacher advises that we （should） review our lessons before doing homework.老师建议我们做作业前先复",
          "习功课。",
          "考点《",
          "find, find out 与 look for 辨析",
          "考点",
          "find",
          "含义及用法",
          "意为“找到；发现”，通常指找到或发现具",
          "体的物品，也可指偶然发现某物或某种情",
          "况，强调“寻找”的结果",
          "示例",
          "I found my lost key under the desk. 我在书桌下",
          "面找到了丢失的钥匙。",
          "WYA下，賀记本",
          "：14",
          "续牧",
          "考点",
          "find out",
          "look for",
          "含义及用法",
          "意为“查明，舜清”，强调经过调查、询问、",
          "打听、研究够一番努力或曲折之后才弄清",
          "楚、弄明白",
          "这为“寻找”，指有目的地找，强调“寻找”",
          "的动作",
          "示例",
          "Let's find out when the train Jeaves. 咱们拼消楚",
          "火车什么时候发车吧。",
          "The little boy is looking for his mother in the",
          "park. 小男孩正在公园里找他妈妈。",
          "考点",
          "vote 的用法",
          "vote 作动词，意为“投票；表决”，常见用法如下：",
          "……"
        ]
      }
    ]
  },
  {
    "unit": "Unit 4",
    "title": "Helping out",
    "levels": [
      {
        "id": "pronunciation",
        "title": "语音知识",
        "summary": "",
        "content": [
          "单元语音知识讲解",
          "紅码理媳",
          "失去爆破",
          "失去燥破是英语发音中的一种语音现象，指任意两个爆破音（/P/，1b/./t/./d/，/K/，/g/）相邻时，前一个",
          "爆破音只做发音口型和动作，但不发出声音（即 “失去爆破”），仅保留极短的停顿后，即发后面的爆破音。如：",
          "I need to find a goo（d） book.",
          "The gizl in the re（d） coat was on a bla（ck） bike.",
          "My brother is so kind that he offers to help tha（t） kid.",
          "（二）"
        ]
      },
      {
        "id": "basics",
        "title": "基础知识",
        "summary": "",
        "content": [
          "单元基础知识背记",
          "重点单词",
          "•名词",
          "1.病毒 n.virus",
          "2.瓶子 n. bottle",
          "3. 考试 1.，exam",
          "4. 阳光 n.sunshine",
          "5.轮椅 n.wheelchair",
          "6.彩色蜡笔 n. crayon",
          "7. X光检查 n.X-ray",
          "8. 士兵，军人 n.. soldier",
          "9.大学；学院 n.college",
          "10.衣袋，口袋 n.pocket",
          "11.对话n.dialogue",
          "12. 流行性感冒，流感n，flu",
          "13.手段；方法；工具 n.means",
          "14.好意，亲普，友善n.goodwill",
          "•动词",
          "1.原谅 w.excuse",
          "2.大学毕业 v.graduate",
          "3.捐贈，捐献 v.donate",
          "4. 买得起 w.afford",
          "5.提到，说起，谈到 v.mention",
          "•形容词",
          "紫色的 adj.purple",
          "•介词",
          "和••⋯对抗 prep.against",
          "•词形变换",
          "1. 有病的；不舒服的adj.il-病，疾病；患病状态7.",
          "illness",
          "2. 温暖的；暖和的adj.warm 温 n.warmth",
          "3.运气 n.luck-运气好的，幸运的 adj. lucky",
          "4.家；住所 n..home--无家可归的adj. homeless",
          "5.请客，款待，招待v.treat一治疗，诊治；疗法n.",
          "treatment",
          "6.解决（问题）v.solve-~解决方法 n.solution",
          "7.消防队员 n.fireman ~（复数）firemen",
          "8. 直接的；亲自的；亲身的 adj. direct-坦率地（直",
          "了当地）adu.directly",
          "9.公开的 adj. public--（反义词）（感情、消息或意见）",
          "个人的，秘密的 adj.private",
          "10. 使失望 v. disappoint一失望的，沮丧的adj.",
          "disappointed-~令人失望的；令人沮丧的；令人扫",
          "兴的 adj. disappointing一失望，扫兴，沮丧n.",
          "disappointment"
        ]
      },
      {
        "id": "phrases",
        "title": "重点短语",
        "summary": "",
        "content": [
          "重点短语",
          "1. 旨在 aim to",
          "2.放弃 give up",
          "3.报名 sign up",
          "4.等待 wait for",
          "5.一瓶 a bottle of",
          "6. 丟弃 throw away",
          "WYA下•帮记本 16",
          "7.患流感 have the flu",
          "8. 处于危险中 in danger",
          "9. 零花钱 pocket money",
          "10. 天生具有 be born with",
          "11. 立刻 right away/at once",
          "12. 因为某人/某物 because of sb. /sth.",
          "13. 增加了•••••increase by.",
          "14. 和⋯⋯分享••⋯•share.with••",
          "15. 传播疾病 spread diseases",
          "16. 需要帮助的 in need of help",
          "17.公开，公之于众 B0 public",
          "18.给某人帮助 give sb.a hand",
          "19. 产生影响 make a difference",
          "20.做家务 do chores/housework",
          "21. 下定决心 make up one's mind",
          "22. 处于极大的痛苦之中 be in great pain",
          "23. 到目前为止，迄今为止 so far/until now",
          "24.绝不，一点儿都不 by no means/not by any means",
          "25. 把某物（尤指建筑物）夷为废墟 reduce sth. to",
          "pieces",
          "26.劳驾（用于礼貌地引起他人注意，尤其是发同时）",
          "excuse me"
        ]
      },
      {
        "id": "sentences",
        "title": "重点句型",
        "summary": "",
        "content": [
          "重点句型",
          "1.到我伸出授手的时候了。",
          "It was time for me to offer mine.",
          "2.她为这家医院增色不少。",
          "She's added colour I this hospital.",
          "3.我一定要做点什么。",
          "There must be something for me to do.",
          "4.恐怕你得画一只灰色的蝴了。",
          "I'm afraid you'll have to draw a grey butterfly.",
          "5.但涂色帮她熬过了这些艰难时刻。",
          "But colouring has helped her get through it.",
          "6.Leah 计划为医院购买五百盒蜡笔。",
          "Leah planned to buy 500 boxes of crayons for the hospital.",
          "7.医院为年幼的病人提供了涂色书。",
          "The hospital provided colouring books for young patients.",
          "8.12年前，她向汶川伸出了援助之手。",
          "She had offered a helping hand to Wenchuan 12 years ago.",
          "9.然后，一双有力的手向我伸来—我得救了。",
          "Then, a pair of strong hands reached out 10 me-1 was saved.",
          "10.那时她和我一样大，也是一个新护士，就像我一样！",
          "At that time she was my age,and also a new nurse,just like me！",
          "11.爱催生爱，进而形成一个善意与仁慈的循环。",
          "Love Leads t love,and so creates e circle of goodwil and kindness.",
          "12.他们日夜争分夺秒地抢救尽可能多的人。",
          "Day and night,they raced against time to save as many people as Possible.",
          "13. 候诊室里现在满是更快乐的孩子和更明亮的照片！",
          "The waiting rooms are now filled with happier kids and brighter pictures！",
          "14.在家人和朋友的帮助下，她举办了许多活动来筹集资金。",
          "With the help of her family and friends, she held many activities to raise money.",
          "17 WYA下，却记本",
          "（三）"
        ]
      },
      {
        "id": "writing",
        "title": "话题范文",
        "summary": "",
        "content": [
          "单元话题范文背记",
          "赠人玫瑰，手有余香。当我们帮助他人的时候，自己也会收获快乐。假如你是学校网站聘请的“快乐大",
          "使”，请你结合自身经历以“My story about happiness”为题，用英语写一篇短文向学校网站投稿，分享你在生活",
          "中帮助他人，传递快乐的小故事。词数80左右。",
          "My story about happiness",
          "I would like to share a heartwarming story about how 1 helped bring happiness to someone in need.",
          "One day,I noriced my Iriend Mary seemed worried because of her poor English. I decided to try my best to",
          "help her. I taught her to remember new words by making word cards. Besides,I also practised speaking English",
          "with her in our spare time. When the result of the final exam came out, I found that Mary had made much",
          "progress. I got such a strong feeling of satisfaction when I saw the joy on her face.",
          "This experience taught me happiness comes from helping others. I will keep on helping those who are in",
          "trouble.",
          "B",
          "春风化雨，润物无声，凡人小事，感动你我。爱心和善举是一种力量，我们应该尽自己最大的努力帮助他",
          "人，因为帮助他人就是帮助自己。某青少年英语网站正在开展以“Every little action matters”为主题的英语征",
          "文活动，请你写一篇英语短文向该网站投稿。词数80左右。",
          "内容包括：",
          "1.谈谈你对人与人之间互帮互助的看法；",
          "2.描述你帮助他人或受他人帮助的一次经历；",
          "3.呼吁大家互帮互助，传递正能量。",
          "Every little action matters",
          "Helping others is really powerful and can change people's lives. 1 believe that when we help others, we'ze",
          "actually helping ourselves.",
          "One day,I was walking home from school when it started raining heavily. I saw an old woman beside me",
          "without an umbrella. Then I offered her my umbrella. She was thankful for my help and we shared a short",
          "conversation. That simple act of kindness warmed my heart and put a smile on her face. Later,when I was in",
          "need of help,my classmates were there for me. These little acts of kindness encouraged me to pay it forward",
          "and help others in need.",
          "It's the small acts of kindness that make a difference in people's lives. Let's all help each other and spread",
          "positive energy.",
          "著点《",
          "afford 的用法",
          "afford 作动词，意为“买得起”，常跟在 can,could,be able to 等之后。afford 的常见用法有：",
          "afford sth.买得起某物",
          "afford的用法",
          "afford to do sth.负担得起做某事",
          "WYA下 食记木18",
          "如：",
          "I can't afford the new TV.我买不起这台新电视。",
          "I hope I can afford to buy a big house one day. 我希望有一天我能买得起一所大房子。",
          "諸点",
          "plan 的用法",
          "动词",
          "plan的用法",
          "一名词",
          "现在分词为planning；过去式为planned",
          "常用结构",
          "可数名词",
          "常用结构",
          "plan sth. 计划某事",
          "plan to do sth. 计划/打算做某事",
          "the plan for sth.对某事的计划/打算",
          "make a plan （to do sth.） 制订计划（做某事）",
          "如：",
          "The plan for a year lies in spring. 一年之计在于春。",
          "Let's make a plan right now.咱们马上就制订计划吧。",
          "They plan to arrive some time after three. 他们预计在三点钟以后到达。",
          "They are planning a party for his birthday.他们正在为他的生日筹划一场派对。",
          "考点",
          "give up 的用法",
          "give up 为“动词＋副词”型短语，意为“放弃”，后接名词、代词或动名词作宾语。名词作宾语时可以放在 give 与",
          "up 之间或 up 之后，代词作宾语时只能放在 give 与 up 之间。如：",
          "Don't give up learning a new language—practice makes perfect！别放弃学习新语言—熟能生巧！",
          "Never give up hope when facing difficulties. 面对困难时永远不要放弃希望。",
          "You should give it up if the task is too dangerous. 如果任务太危险，你应该放弃。",
          "【拓展】由 give 构成的其他常用短语",
          "give away 捐赠；泄露",
          "give",
          "相关短语",
          "give in 届服",
          "give out 分发；散发",
          "give back 归还",
          "give off 发出；放出",
          "考点",
          "spread 的用法",
          "spread的用法",
          "作动词，意为“传播；展开”，过去式和过去分词均为spread。",
          "常见用法：spread...around 到处传播⋯⋯",
          "作名词，意为“蔓延；传播”",
          "如：",
          "She spread the good news around the office as soon as she heard it. 她一听到这个好消息，就立刻在办公室里传",
          "开了。",
          "The bird spreads its wings ready for flight.鸟儿展开翅膀准备飞翔。",
          "The spread of the disease has been controlled.疾病的传播已经得到了控制。",
          "19",
          "脂点<5",
          "public 的用法",
          "Public 作形容词，意为“公开的”，通常作定语修饰名词。常见用法有，",
          "They didn't wantthe problem to go public.",
          "他们不想让问题公开化。",
          "……"
        ]
      }
    ]
  },
  {
    "unit": "Unit 5",
    "title": "Looking into nature",
    "levels": [
      {
        "id": "pronunciation",
        "title": "语音知识",
        "summary": "",
        "content": [
          "单元语音知识讲解",
          "名词和动词的重音",
          "在英语里，部分双音节词兼具名词和动词词性。当作名词使用时，重音多落在第一个音节。比如 object，",
          "作名词表示“物体；目标”，读音是/'obdgikst/，重音在“ob”音节；而作动词表示“反对”，读音是/ab'dgekt/，重",
          "音移到了“ject”音节。又如 present，作名词表示“礼物；现在”，读音为/'preant/，重音在前；作动词“赠送；呈",
          "现”，读音是/prlzent/，重音在后。这种重音的变化有助于区分词性，在口语交流中能让听者更清晰地判断说话",
          "者使用该词的词性和语义。从语言发展角度看，这种重音的变化是长期语言使用习惯形成的一种语音区分机制。",
          "名词",
          "increase 增长；增长盘",
          "progress 进步；进展",
          "project 项目；方案",
          "record 记录；唱片",
          "动词",
          "increase（使）增长，增多；增加",
          "progress 改进；进展",
          "project 规划；计划",
          "record 记录；承制",
          "听并跟读下列对话，体会画线单词的重音和词性变化。",
          "Mary: Thank you for the book, Jack. I's a nice present. 1 project to do a research on stars. It will be useful for",
          "my reasearch.",
          "Jack: I'm sure it will help you increase your understanding of the topic. By the way, how's your project? Is it",
          "progressing smoothly？",
          "Mary: I'm making good progress. I'Il present it next week.",
          "（二）"
        ]
      },
      {
        "id": "basics",
        "title": "基础知识",
        "summary": "",
        "content": [
          "单元基础知识背记",
          "重点单词",
          "名词",
          "1.鲸n.whale",
          "2. 风格 n. style",
          "3.蜥蜴 n.. lizard",
          "4. 琥珀 n.amber",
          "5.模型7.model",
          "6.行星 n. planet",
          "7.财富 n.wealth",
          "8. 物种 7. species",
          "9.恐龙n.dinosaur",
          "10.报纸 n. newspaper",
          "11.放大镜 n.magnifier",
          "12. 文字材料 n.text",
          "13.羽毛，翎n.feather",
          "14.视力，视觉 n.sight",
          "15.方法，办法 n.method",
          "16. 布告牌，公告牌 n.board",
          "17. 孙女；外孙女 n.granddaughter",
          "•动词",
          "1.清除：消理 v.clear",
          "2.应在（某处） .belong",
          "•形容词",
          "1.羽毛覆盖的 adj.feather-covered",
          "2.有活力的，有生气的adj. alive",
          "副词",
          "几乎不 adv. hardly",
          "•其他",
          "1.任何人 pron.anybody",
          "2. 是否（用于表示选择或对某事不确定）conj.",
          "whether",
          "词形变换",
          "1.书写 v.write-写作，著书 n.wtiting",
          "2.北方 n. north-~北部的 adj. northern",
          "3. 相信；认 v.believe--观点 n.belief",
          "4.争论 v.argue--论点，论据 1.argument",
          "5. 化学 n.chemistry 化学品 n.chemical",
          "6.非洲 n.Africa 非洲的，非洲人的adj. African",
          "7.（用锁）锁上；被锁住v.lock -揭开v.unlock",
          "8.满的 adj. full--完全地；充分地：彻底地 adu. fully",
          "9.结束，尽头 n.end--无数的，无限的adj. endless",
          "10. 上载，上传v.upload-（反义词）下载v.download",
          "11.（使）沸腾；煮沸；烧开v.boil--很热的，滚热的",
          "adj. boiling",
          "12. 知道2. know--知名的；已知的adj. known-~（反",
          "义词）不知道的，未知的 adj.unknown",
          "WY八下•背记木"
        ]
      },
      {
        "id": "phrases",
        "title": "重点短语",
        "summary": "",
        "content": [
          "重点短语",
          "1.生病 fall ill",
          "2，不再 nolonger",
          "3.于 belong to",
          "4. 去世 pass away",
          "5. 落叶 falling leaves",
          "6. 太阳系 solar system",
          "7. 观察；探究 look into",
          "8. 花季 flowering season",
          "9.幸亏；由于 chanks to",
          "10. 致力于 put effort into",
          "11.过去经常（发生），曾经 used to （do）",
          "12.有机会做某事 get to do sth.",
          "13. 自然探索 nature exploration",
          "14.⋯⋯的开端 the beginning of",
          "15.实施：执行：开展 carry out",
          "16.完全地；自始至终地 all the way",
          "17.继续某事 carry on with.sth.",
          "18.妨碍某人；挡某人的路 in one's way",
          "19.对⋯•（感到）好奇 be curious about",
          "20. 揭开某事的秘密 unlock the secrets of sth.",
          "21.对•保持沉默；不声张 be quiet about",
          "22.唤起/激发某人的好奇心 awaken one's curiosity",
          "23. 主动向某人呈现某物；向某人提供某物 present",
          "sb. with sth."
        ]
      },
      {
        "id": "sentences",
        "title": "重点句型",
        "summary": "",
        "content": [
          "重点句型",
          "1.大自然为我们星现着无尽的奇迹。",
          "Nature presents us with endless wonders.",
          "2.它正在四处奔跑，寻觅它的下一餐。",
          "It is running around,looking for its next meal.",
          "3. 作为一扇通往过去的窗口，現珀已被深人研究。",
          "As e window on the past, amber has been much studied.",
          "4.但有一个人，将他的兴趣延续到了田野之间。",
          "But one person took his interest all the way to the fields.",
          "5.有一次，在云南进行野外考察时，他身染重病。",
          "Once,he fell seriously 山 while doing field work in Yunnan.",
          "6.它们能告诉我们恐龙是否有羽毛，但这并非全部。",
          "They can tell us whether dinosaurs had feathers, but that's not all.",
          "7.为了进行研究，他长年累跋涉于深山密林之间。",
          "To carry out his research,he spent years in wild mountains and forests.",
          "8.此前，科学家们认为蚂蚁起源于北半球。",
          "Scientists used I6 believe that ants came from the northern half of the earth.",
          "9.尽管成就卓著，王（先生）却很少考虑个人荣誉或财富。",
          "Despite his huge success, Wang seldom thought about personal honour or wealth.",
          "10.借助放大镜，他又潜心钻研了十年。",
          "With a magnifier in hand,he still carried on with his research for another 10 years.",
          "11.未来，现珀或许还能帮助我们发现其他物种是否随时间发生了变化。",
          "In the future,amber may also help us discover if other species have changed over time.",
          "12.这个物种如今在该地区已绝迹。但这一发现证明，3500万年前它确实生长于此。",
          "This species no longer grows in this area. But the find proves that it did 35 million years ago.",
          "23 WY八下，背记本",
          "（三）"
        ]
      },
      {
        "id": "writing",
        "title": "话题范文",
        "summary": "",
        "content": [
          "单元话题范文背记",
          "A",
          "在我们的生活中，有很多亲近大自然的方式，如登山、种树、露营、赏花、观鸟等。假如你是膝飞，请你根据",
          "以下提示问题，写一篇英语短文，分享你与大自然之间的故事。词数80词左右。",
          "1. What's your favourite way to get close to nature Clike hiking,camping,tree planting,bird watching...）？",
          "2. Why do you like the way best？",
          "3. What can you do for nature？",
          "Getting close to nature",
          "My name is Teng Fei, and I really like getting close to nature. My favourite way is hiking. Every weekend，",
          "I climb the nearby hills with my family or friends. I love studying the different plants along the path—beautiful",
          "wildflowers, tall trees, and sometimes even small animals like squirrels.",
          "When 1 stand high above,watching the beautiful landscape,I feel a deep connection with nature. It reminds",
          "me of how beautiful our world is.",
          "Hiking not only keeps me healthy but also teaches me to respect and protect the natural world. T'll choose",
          "to walk or ride a bike to school instead of taking a car to cut down air pollution. I believe these small actions can",
          "make a big difference to nature.",
          "B",
          "你的外教老师 MI Smith 正在组织一场关于“榜样的力量”的英语写作活动。请你根据以下要点提示，写",
          "一篇英语短文，介绍一位自然探索领域的榜样。词数80词左右。",
          "内容包括：",
          "1.简单介绍他/她；",
          "2.你从他/她身上学到了什么品质；",
          "3.你打算如何在生活中践行这些品质。",
          "Great nature explorer一Charles Darwin",
          "I've always been interested in nature explorers. Take Charles Darwin as an example. He spent years",
          "travelling and studying nature. Many of his books tell stories about his adventures in nature and changed how",
          "people understand life on the earth.",
          "From Darwin,I learn two key qualities. First,he was curious about everything around him,always asking",
          "“why\". Second,he was patient and hard-working,even when facing challenges.",
          "In my daily life,I will follow his example. T'll pay more attention to small things around me,like how birds",
          "build nests. When I find science projects difficult,I'Il try again and again, just like he did. This will help me",
          "understand nature better！",
          "（四）"
        ]
      },
      {
        "id": "points",
        "title": "重要考点",
        "summary": "",
        "content": [
          "单元重要考点背记",
          "考点",
          "whether 的用法",
          "whether 作连词，意为“是否”，用于引导不确定或选择性的内容，在宾语从句中，多数情况下可与i互换。如：",
          "We're discussing whether/if we should change the plan. 我们正在讨论是否应该改变计划。",
          "【注意】宾语从句中只能用 whether，不能用if的情况：",
          "①宾语从句中和 or not 连用时。如：",
          "She wants to know whether or not you're free.她想知道你是否有空。",
          "WY八下•背记本",
          "②宾语从句与 or 构成选择结构时。如：",
          "He can't tell whether it's raining or snowing. 他分不清是下雨还是下雪。",
          "③宾语从句后接动词不定式时。如：",
          "I can't decide whether to accept the offer.我无法决定是否接受这个提议。",
          "④宾语从句位于介词之后时。如：",
          "Everything depends on whether you agree. 一切取决于你是否同意。",
          "煮点",
          "alive, living,live 与 lively 辨析",
          "考点",
          "alive",
          "living",
          "live",
          "lively",
          "考点《",
          "词性、含义及用法",
          "示例",
          "作形容词，意为“活着的；有生气的；变得兴味盎",
          "He is one of the greatest artists alive today. 他是当",
          "然；生动起来”，修饰人或动植物，可作表语、宾语",
          "今在世的最伟大的艺术家之一。",
          "补足语或后置定语，但不能用在名词前作定语",
          "作形容词，意为“活着的”，修佈人或物，可作表",
          "All living things need water. 一切生物都需要水。",
          "语或前置定语。作表语时，相当于 alive",
          "He said he had seen a live whale. 他说他见过活鲸鱼。",
          "作形容词，意为“活的；有生命的；现场直播的”，",
          "We watched the live broadcast of the concert on",
          "修饰人或物，一般作前置定语",
          "TV.我们在电视上观看了音乐会的现场直播。",
          "作形容词，意为“活泼的；生气勃勃的”，修佈人",
          "She was very lively at the party. 她在聚会上非常",
          "或物，常用来描述人及其行为或活动，可作表语",
          "活跃。",
          "或定语",
          "clear 的用法",
          "清除；清理",
          "Clear all those papers off the desk.把桌子上所有那些文件都拿走。",
          "clear",
          "的用法",
          "作动词",
          "天气放晴",
          "The sky cleared afier the storm.桑风雨过后，天转晴了。",
          "Thc traffic took a long time to clear after the accident.事故过去后",
          "很长时间交通才恢复畅通。",
          "（路面）畅通",
          "【拓展】clear还可以作形容词，意为“清楚易懂的；清晰的；清澈明亮的；明显的”。",
          "匿点（42常见否定前缀",
          "考点",
          "用法",
          "un-",
          "可加在形容词、动词、名词前表",
          "示否定",
          "im-",
          "用于以 p,b,m 开头的单词前",
          "dis-",
          "25 WYA下 將记本",
          "加在动词、形容词、名词前，表相",
          "反动作或剥夺，强调对立关系",
          "示例",
          "known 知道的—unknown 不知道的；未知的",
          "lock 锁上-runlock 解锁",
          "employment 雇佣；就业 -~unemployment失业",
          "possible 可能的-~impossible 不可能的",
          "balance 平衡--imbalance 不平衡",
          "mobile 可移动的；非固定的-rimmobile 固定的",
          "appear 出现一disappear 消失",
          "honest 诚实的-dishonest 不诚实的",
          "like 喜欢-~dislike 不喜欢",
          "beloug to 的用法",
          "belong to 是一个常用的动词短语，意为“瓜于，归⋯⋯所有，是⋯⋯的成员，是⋯",
          "…的一部分”。belong to 中的",
          "t0 为介词，后接名词或人称代词的宾格。如：",
          "This book belongs to my father/him，这本书属于我的爸爸/他。",
          "【拓展】“belong 10十名词/人称代词的宾格”结构可与名词性物主代词或名词所有格进行同义转换。如：",
          "The yellow car belongs to me. = The yellow car is mine. 那辆黄色的车是我的。",
          "【注意】bclong to 不用于进行时态和被动语态。",
          "考点",
          "used to 的用法",
          "“主语十used to”后接动词原形时，用于表示过去一度存在或经常发生，但现在已经不存在的动作或状态，且其",
          "不与表示过去的时间状语连用。used to的否定形式是 “didn't use to\" 或 “used not to（usedn't to）”。如：",
          "Coach Lang Ping used to encourage Zhu Ting with the following words。郎平教练曾经用下面的话鼓励朱婷。",
          "……"
        ]
      }
    ]
  },
  {
    "unit": "Unit 6",
    "title": "Living with nature",
    "levels": [
      {
        "id": "pronunciation",
        "title": "语音知识",
        "summary": "",
        "content": [
          "单元语音知识讲解",
          "扫码晨",
          "复合名词的重音",
          "在英语中，复合名词的重音通常落在第一个词，第二个词弱读。如：bookstore 作名词表示“书店”，是由",
          "“book（书）+store（商店）”组成，读音是/'buksto：（r）/，重音在 “book”音节。sunlight 作名词表示“阳光”，是",
          "由 “sun（太阳）＋light（光）”组成，读音是/sAnlatt/，重音在 “sun” 音节。这种重音规则有助于区分复合名词与",
          "普通短语，在口语交流中能让听者更清晰地判断说话者表达的是整体概念还是独立词义。",
          "听并跟读下列句子。",
          "The garden is full of tall sunflowers.",
          "I spent two hours on my homework last night.",
          "After the storm, we saw a beautiful rainbow.",
          "The teacher wrote the maths problem on the blackboard.",
          "The highway is busy with cars at weekends.",
          "We saw many kinds of wildlife in the forest.",
          "I have a headache,so I need to rest.",
          "（二）"
        ]
      },
      {
        "id": "basics",
        "title": "基础知识",
        "summary": "",
        "content": [
          "单元基础知识背记",
          "重点单词",
          "名词",
          "1.小麦 n.wheat",
          "2.省 n. province",
          "3.水渠，沟渠；运河 7.canal",
          "4. 兩量 7. rainfall",
          "5.历法 n.calendar",
          "6. 养蜂 1.bee-keeping",
          "7.沙漠，荒漠 n.desert",
          "8. 仲夏 n.midsummer",
          "9.生态环境 n. environment",
          "10. 乡下，农村 n. countryside",
          "11. 增加，增多；增长 n. increase",
          "12. 资源 n.resource",
          "•动词",
          "1.（使）充电 w.charge",
          "2. 活下来；幸存 u.survive",
          "3.（作出）反应 v. react",
          "•形容词",
          "1.疯狂的 adj.crazy",
          "2.地（面）下的 adj. underground",
          "•介词",
          "1. 在⋯…的下面 prep.below",
          "2.是•…之一 prep.among",
          "•词形变换",
          "1.到达 n.arrive--到来 n.arrival",
          "2.村庄 n. village一村民 n. villager",
          "3. 明智的 adj. wise-智慧，才智 n.wisdom",
          "4.矮的；短的 adj. short一短缺，不足，缺乏 n.",
          "shortage",
          "5.特别的，特殊的 adj. especial-尤其 adv. especially",
          "6. 东部 n. east （某国家或地区）东部的adj.eastern",
          "7.很可能发生（或存在等）的adj.probable-~很可能，",
          "大概 adu. probably",
          "8.西，西面 n.west （某国家或地区）西部的adj.",
          "western",
          "9.能源 n.energy一精力充沛的，充满活力的adj.",
          "energetic",
          "10. 甜蜜的；悦耳的 adj.sweet一悦耳动听地，好听地",
          "adv.sweetly"
        ]
      },
      {
        "id": "phrases",
        "title": "重点短语",
        "summary": "",
        "content": [
          "重点短语",
          "1. 捡起 pick up",
          "2. 落入 「all into",
          "3.难 no wonder",
          "4.利用 make useof",
          "S. 日常生活 daily life",
          "6.贴近 stay close to",
          "7.即使 oven though",
          "8.太阳能 solar energy",
          "9.采取行动 takc action",
          "10. 以这种方式 this way",
          "11.与⋯⋯一样 as⋯.•as⋯",
          "12. 渴望：份望 long to do",
          "13. 气候变化 climate change",
          "14. 即将开始做某事 be set to",
          "15.远离⋯•move away from",
          "16. 太阳能电池板 solar pancls",
          "17. 文化意义 cultural meanings",
          "18. 自然资源 natural resources",
          "19.水资源短缺 water shortage",
          "20.现代技术 modern technology",
          "21. 以⋯⋯而用名 be known as",
          "22. 从⋯•消失 disappear from",
          "23.对⋯••有害 be harmful for",
          "24.在特定的时刻 at certain times",
          "25.把⋯••变成•••••turn••into•",
          "26. 从⋯…中受益 benefit from",
          "27. 在•••的东部 in the east of",
          "28. 起重要作用 play an important role",
          "29.根据自然法则 by the laws of nature",
          "30.匆忙（去莱地/做某事）hurry to",
          "31.与…•",
          "••和谐相处 live in harmony with",
          "32. 据⋯⋯所示：按•••所说 according to"
        ]
      },
      {
        "id": "sentences",
        "title": "重点句型",
        "summary": "",
        "content": [
          "重点句型",
          "1.那几乎与赏河一样长！",
          "That's nearly as Jong the Yellow River！",
          "2.那里的村民大多以务农为生。",
          "Most of the villagers there lived by farming.",
          "3.秘密就在于古老的坎儿井系统。",
          "The secret lies in the ancient karez system.",
          "4.它被誉为世界上最热的地区之一。",
          "It's known as one of the hottest areas in the world.",
          "5. 人们用传统活动来庆祝它们的到米。",
          "People celebrate their arrival with traditional activities.",
          "6.我不知道这些画作会变得多么受欢迎。",
          "I didn't know how popular the paintings would become.",
          "7. 它们帮助人们理解为什么大自然会以这种方式运作。",
          "They help people understand why nature works this way.",
          "8. 我渴望通过绘画和诗歌与人分享这些感受。",
          "I longed 1o share these feelings in my paintings and poems.",
          "9.令人惊奇的是，所有这一切都是仅用手工工具完成的。",
          "And amazingly,all of this was completed with only hand tools.",
          "WY入下 智史太",
          "10.许多节气也都承 着社会与文化意义。",
          "Many of the 24 Solar Terms bear social and cultural meanings,too.",
          "11.尽管现代技术正在解决一些问题，但坎儿井系统仍然发挥着重要作用。",
          "Although modern technology is solving some problems, the karez system still plays an important role.",
          "12.我很高兴许多人，尤其是年轻人，正在对古老的产生新的兴趣。",
          "I'm so happy that many people,especially the young,are taking e new interest in the ancient wisdom.",
          "（三）"
        ]
      },
      {
        "id": "writing",
        "title": "话题范文",
        "summary": "",
        "content": [
          "单元话题范文背记",
          "A",
          "在人类发展历程中，人们为满足自身需求，对自然环境进行了诸多改造。请你根据下面的内容提示，以",
          "“How people change nature”为题，写一篇英语短文。词数80词左右。",
          "内容包括：",
          "1. What is the example of changing nature？",
          "2. Where is it? When did it start？",
          "3. What are some amazing facts？",
          "4. Give your opinion about changing nature.",
          "How people change nature",
          "People often change nature to meet their needs. A good example is the Three Gorges Dam in China. It was",
          "built on the Yangtze River. The construction started in 1994.",
          "The dam is huge and amazing. It's about 2,309 metres long and 185 metres high. It works by blocking the",
          "river to store water. The stored water is used to produce electricity,which provides power for many cities.",
          "Besides,the dam plays an important role in flood control. It stores extra water during heavy rains, so it can",
          "protect people living along the river from floods.",
          "Although it brings benefits,we should always think about how to balance human development and nature",
          "protection. After all,we should live in harmony with nature, not against it.",
          "B",
          "4月22日是世界地球日，“珍爱地球 人与自然和谐相处”是2024年世界地球日的主题。请你以“Live",
          "harmony with nature”为题，谈一谈作为中学生，我们可以从哪些方面让家和学校更环保、更美丽。词数80词",
          "左右。",
          "内容包括：",
          "1. What resources can you save？",
          "2. What can you do to protect the environment？",
          "Live harmony with nature",
          "22 April is World Earth Day. In 2024, its theme was about living harmony with nature. As middle school",
          "students,we can take action from now.",
          "At school, we can save paper by using both sides. Also,turn off lights when leaving classrooms to save",
          "electricity. At home,reuse water for watering plants after washing vegetables. All these methods can do good to",
          "our natural resources.",
          "Besides,we should sort waste to recycle useful things. Picking up litter around and planting more trees are",
          "also good ways. Small steps can make a big difference to our home and school, and help protect the earth.",
          "29",
          "（四）"
        ]
      },
      {
        "id": "points",
        "title": "重要考点",
        "summary": "",
        "content": [
          "单元重要考点背记",
          "医点",
          "long 的用法",
          "long 作动词，意为“渴望”，其常见用法如下：",
          "long to do sth.渴望做某事",
          "Ilong to travel around the world. 我渴望环游世界。",
          "long的用法",
          "She longs for peace and quict.她渴望平静与安宁。",
          "long for sth.渴望某物",
          "嗜涼及",
          "below 的用法",
          "There stands a chair below the window.窗户下面",
          "放着一把椅子。",
          "（地方或位置）在⋯⋯下面",
          "作介词",
          "The temperature in our hometown usually",
          "drops below zero in winter. 我们家乡冬天",
          "7的气温通常降到零摄氏度以下。",
          "（数量、水平等）在⋯•⋯以下，低于",
          "below",
          "的用法",
          "Please read the instructions below. 请阅读下面的说明。",
          "作副词",
          "在下面",
          "看点",
          "be known as 与 be known for 辨析",
          "考点",
          "含义及用法",
          "示例",
          "be known as",
          "表示“以……用名”，一般后接职业、称",
          "呼或身份地位",
          "She is known as a talented painter.她以天才画",
          "家的身份闻名。",
          "be known for",
          "表示“因某事物/特点而同名”，一般后",
          "接具体特点、技能、成就或事物",
          "The city is known for its ancient architecture.",
          "这座城市因古建筑而用名。",
          "證点 42among 与 between 辨析",
          "考点",
          "用法",
          "示例",
          "among",
          "用于三者或三者以上的人或事物之中",
          "There is a beautiful garden among the buildings.在这",
          "些建筑物之同有一个美丽的花园。",
          "between",
          "用于两者之间，常与and 连用，一般构成",
          "双方关系的都可用between",
          "It's important to manage your time well between",
          "study and relaxation. 在学习和放松之间合理安排时",
          "间是很重要的。",
          "【注意】指三者或三者以上的人或事物中的两者之同时，仍用between。如：",
          "We have four classes in the morning and we take a break between classes. 上午我们有四节课，每两节课之间",
          "我们会休息一下。",
          "WY 八下•背记本",
          "醫点",
          "In,on,1o表示空间地理位置时的辦析",
          "考点",
          "含义及用法",
          "in",
          "A 在B地内部（包含关系）",
          "on",
          "A 与B接壤（相邻且接触）",
          "to",
          "A 与B不接壤（相邻但不接触）",
          "考点",
          "as••as 结构的用法",
          "考点",
          "含义及用法",
          "as十形容词/副词原级十as",
          "和⋯⋯一样⋯⋯",
          "not as/so十形容词/副词原级十as",
          "不如…⋯",
          "倍数十as十形容词/副词原级十as",
          "表示倍数关系",
          "示例",
          "Shanghai is in the east of China， 上海在中国的东部。",
          "Fujian is on the east of Jiangxi， 福建在江西的东边。",
          "Japan lies to the east of China. 日本位于中国的东边。",
          "as much/many＋名词+as",
          "as十形容词/副词原级十as possible",
          "考点",
          "表示数量程度",
          "尽可能⋯…",
          "示例",
          "She is as tall as her sister.她和姐姐一样商。",
          "Tom runs as fast as Mike. 汤姆跑得和迈克一样快。",
          "This movie is not as exciting as the last one. 这部电",
          "……"
        ]
      }
    ]
  }
];
