export const unit5Challenge = {
  unit: "Unit 5",
  title: "第五单元背记闯关",
  levels: [
    {
      id: "word-forms",
      title: "词性回响",
      type: "word-family",
      prompt: "同一词根一起考，根据中文和词性写英文，不给首字母。",
      items: [
        { root: "write", forms: [{ clue: "书写 v.", answer: "write" }, { clue: "写作，著书 n.", answer: "writing" }] },
        { root: "north", forms: [{ clue: "北方 n.", answer: "north" }, { clue: "北部的 adj.", answer: "northern" }] },
        { root: "believe", forms: [{ clue: "相信；认为 v.", answer: "believe" }, { clue: "观点 n.", answer: "belief" }] },
        { root: "argue", forms: [{ clue: "争论 v.", answer: "argue" }, { clue: "论点，论据 n.", answer: "argument" }] },
        { root: "chemistry", forms: [{ clue: "化学 n.", answer: "chemistry" }, { clue: "化学品 n.", answer: "chemical" }] },
        { root: "Africa", forms: [{ clue: "非洲 n.", answer: "Africa" }, { clue: "非洲的，非洲人的 adj.", answer: "African" }] },
        { root: "lock", forms: [{ clue: "（用锁）锁上；被锁住 v.", answer: "lock" }, { clue: "揭开 v.", answer: "unlock" }] },
        { root: "full", forms: [{ clue: "满的 adj.", answer: "full" }, { clue: "完全地；充分地；彻底地 adv.", answer: "fully" }] },
        { root: "end", forms: [{ clue: "结束；尽头 n.", answer: "end" }, { clue: "无数的，无限的 adj.", answer: "endless" }] },
        { root: "upload", forms: [{ clue: "上载，上传 v.", answer: "upload" }, { clue: "下载 v.", answer: "download" }] },
        { root: "boil", forms: [{ clue: "（使）沸腾；煮沸；烧开 v.", answer: "boil" }, { clue: "很热的，滚热的 adj.", answer: "boiling" }] },
        { root: "know", forms: [{ clue: "知道 v.", answer: "know" }, { clue: "知名的；已知的 adj.", answer: "known" }, { clue: "不知道的，未知的 adj.", answer: "unknown" }] },
      ],
    },
    {
      id: "phrases",
      title: "短语补给",
      type: "full",
      prompt: "根据中文写英文短语，不给首字母。",
      items: [
        { clue: "生病", answer: "fall ill" },
        { clue: "不再", answer: "no longer" },
        { clue: "属于", answer: "belong to" },
        { clue: "去世", answer: "pass away" },
        { clue: "落叶", answer: "falling leaves" },
        { clue: "太阳系", answer: "solar system" },
        { clue: "观察；探究", answer: "look into" },
        { clue: "花季", answer: "flowering season" },
        { clue: "幸亏；由于", answer: "thanks to" },
        { clue: "致力于", answer: "put effort into" },
        { clue: "过去经常（发生），曾经", answer: "used to" },
        { clue: "有机会做某事", answer: "get to do sth." },
        { clue: "自然探索", answer: "nature exploration" },
        { clue: "……的开端", answer: "the beginning of" },
        { clue: "实施；执行；开展", answer: "carry out" },
        { clue: "完全地；自始至终地", answer: "all the way" },
        { clue: "继续某事", answer: "carry on with sth." },
        { clue: "妨碍某人；挡某人的路", answer: "in one's way" },
        { clue: "对……（感到）好奇", answer: "be curious about" },
        { clue: "揭开某事的秘密", answer: "unlock the secrets of sth." },
        { clue: "对……保持沉默；不声张", answer: "be quiet about" },
        { clue: "唤起/激发某人的好奇心", answer: "awaken one's curiosity" },
        { clue: "主动向某人呈现某物；向某人提供某物", answer: "present sb. with sth." },
      ],
    },
    {
      id: "sentences",
      title: "句型裂隙",
      type: "sentence",
      prompt: "根据中文和英文句子，填写划线处单词或短语，不给首字母。",
      items: [
        { clue: "大自然为我们呈现着无尽的奇迹。", sentence: "Nature ____ endless wonders.", answer: "presents us with" },
        { clue: "它正在四处奔跑，寻觅它的下一餐。", sentence: "It is running around, ____ its next meal.", answer: "looking for" },
        { clue: "作为一扇通往过去的窗口，琥珀已被深入研究。", sentence: "As a ____ the past, amber has been much studied.", answer: "window on" },
        { clue: "但有一个人，将他的兴趣延续到了田野之间。", sentence: "But one person took his interest ____ to the fields.", answer: "all the way" },
        { clue: "有一次，在云南进行野外考察时，他身染重病。", sentence: "Once, he ____ while doing field work in Yunnan.", answer: "fell seriously ill" },
        { clue: "它们能告诉我们恐龙是否有羽毛，但这并非全部。", sentence: "They can tell us ____ dinosaurs had feathers, but that's not all.", answer: "whether" },
        { clue: "为了进行研究，他长年累月跋涉于深山密林之间。", sentence: "To ____ his research, he spent years in wild mountains and forests.", answer: "carry out" },
        { clue: "此前，科学家们认为蚂蚁起源于北半球。", sentence: "Scientists ____ that ants came from the northern half of the earth.", answer: "used to believe" },
        { clue: "尽管成就卓著，王先生却很少考虑个人荣誉或财富。", sentence: "____ his huge success, Wang seldom thought about personal honour or wealth.", answer: "Despite" },
        { clue: "借助放大镜，他又潜心钻研了十年。", sentence: "With a magnifier in hand, he still ____ his research for another 10 years.", answer: "carried on with" },
        { clue: "未来，琥珀或许还能帮助我们发现其他物种是否随时间发生了变化。", sentence: "In the future, amber may also help us discover ____ other species have changed over time.", answer: "if" },
        { clue: "这个物种如今在该地区已绝迹。", sentence: "This species ____ grows in this area.", answer: "no longer" },
      ],
    },
  ],
};
