export const vocabulary = [
  {
    "id": "w001",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 4,
    "type": "单词",
    "word": "spiderman",
    "phonetic": "/ˈspaɪdəmæn/",
    "partOfSpeech": "n.",
    "meaning": "蜘蛛人；高空作业工人",
    "note": ""
  },
  {
    "id": "w002",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 4,
    "type": "单词",
    "word": "wet",
    "phonetic": "/wet/",
    "partOfSpeech": "adj.",
    "meaning": "湿的；潮的；潮湿的",
    "note": ""
  },
  {
    "id": "w003",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 4,
    "type": "单词",
    "word": "drop",
    "phonetic": "/drɒp/",
    "partOfSpeech": "n.",
    "meaning": "滴；水滴",
    "note": ""
  },
  {
    "id": "w004",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 4,
    "type": "单词",
    "word": "sweat",
    "phonetic": "/swet/",
    "partOfSpeech": "n.",
    "meaning": "汗；汗水",
    "note": ""
  },
  {
    "id": "w005",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 4,
    "type": "单词",
    "word": "watermelon",
    "phonetic": "/ˈwɔːtəmelən/",
    "partOfSpeech": "n.",
    "meaning": "西瓜",
    "note": ""
  },
  {
    "id": "w006",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 4,
    "type": "单词",
    "word": "remind",
    "phonetic": "/rɪˈmaɪnd/",
    "partOfSpeech": "v.",
    "meaning": "使想起；提醒",
    "note": ""
  },
  {
    "id": "w007",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 4,
    "type": "单词",
    "word": "newborn",
    "phonetic": "/ˈnjuːbɔːn/",
    "partOfSpeech": "adj.",
    "meaning": "新生的",
    "note": ""
  },
  {
    "id": "w008",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 5,
    "type": "单词",
    "word": "brush",
    "phonetic": "/brʌʃ/",
    "partOfSpeech": "n.",
    "meaning": "刷子；毛刷",
    "note": ""
  },
  {
    "id": "w009",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 6,
    "type": "单词",
    "word": "speech",
    "phonetic": "/spiːtʃ/",
    "partOfSpeech": "n.",
    "meaning": "演说；演讲",
    "note": ""
  },
  {
    "id": "w010",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 6,
    "type": "单词",
    "word": "challenging",
    "phonetic": "/ˈtʃælɪndʒɪŋ/",
    "partOfSpeech": "adj.",
    "meaning": "富于挑战性的；困难而有趣的",
    "note": ""
  },
  {
    "id": "w011",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 6,
    "type": "单词",
    "word": "context",
    "phonetic": "/ˈkɒntekst/",
    "partOfSpeech": "n.",
    "meaning": "上下文；语境",
    "note": ""
  },
  {
    "id": "w012",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 7,
    "type": "单词",
    "word": "company",
    "phonetic": "/ˈkʌmpəni/",
    "partOfSpeech": "n.",
    "meaning": "公司",
    "note": ""
  },
  {
    "id": "w013",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 7,
    "type": "单词",
    "word": "interview",
    "phonetic": "/ˈɪntəvjuː/",
    "partOfSpeech": "n.",
    "meaning": "面试；面谈",
    "note": ""
  },
  {
    "id": "w014",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 7,
    "type": "单词",
    "word": "communication",
    "phonetic": "/kəˌmjuːnɪˈkeɪʃən/",
    "partOfSpeech": "n.",
    "meaning": "信息交流；沟通",
    "note": ""
  },
  {
    "id": "w015",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 7,
    "type": "单词",
    "word": "skill",
    "phonetic": "/skɪl/",
    "partOfSpeech": "n.",
    "meaning": "技能；技巧；技艺",
    "note": ""
  },
  {
    "id": "w016",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 7,
    "type": "单词",
    "word": "personality",
    "phonetic": "/ˌpɜːsəˈnæləti/",
    "partOfSpeech": "n.",
    "meaning": "个性；性格",
    "note": ""
  },
  {
    "id": "w017",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 7,
    "type": "单词",
    "word": "require",
    "phonetic": "/rɪˈkwaɪə/",
    "partOfSpeech": "v.",
    "meaning": "需要",
    "note": ""
  },
  {
    "id": "w018",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 7,
    "type": "单词",
    "word": "organise",
    "phonetic": "/ˈɔːɡənaɪz/",
    "partOfSpeech": "v.",
    "meaning": "组织；筹划；安排",
    "note": ""
  },
  {
    "id": "w019",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 7,
    "type": "单词",
    "word": "leadership",
    "phonetic": "/ˈliːdəʃɪp/",
    "partOfSpeech": "n.",
    "meaning": "领导才能；领导素质",
    "note": ""
  },
  {
    "id": "w020",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 10,
    "type": "单词",
    "word": "career",
    "phonetic": "/kəˈrɪə/",
    "partOfSpeech": "n.",
    "meaning": "职业；事业",
    "note": ""
  },
  {
    "id": "w021",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 13,
    "type": "单词",
    "word": "cashier",
    "phonetic": "/kæˈʃɪə/",
    "partOfSpeech": "n.",
    "meaning": "出纳员；收银员",
    "note": ""
  },
  {
    "id": "w022",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 13,
    "type": "单词",
    "word": "necessary",
    "phonetic": "/ˈnesəsəri/",
    "partOfSpeech": "adj.",
    "meaning": "必要的；必需的；不可少的",
    "note": ""
  },
  {
    "id": "w023",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 13,
    "type": "单词",
    "word": "replace",
    "phonetic": "/rɪˈpleɪs/",
    "partOfSpeech": "v.",
    "meaning": "取代",
    "note": ""
  },
  {
    "id": "w024",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 13,
    "type": "单词",
    "word": "pilot",
    "phonetic": "/ˈpaɪlət/",
    "partOfSpeech": "n.",
    "meaning": "飞行员；驾驶员",
    "note": ""
  },
  {
    "id": "w025",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 13,
    "type": "单词",
    "word": "autopilot",
    "phonetic": "/ˈɔːtəʊˌpaɪlət/",
    "partOfSpeech": "n.",
    "meaning": "自动驾驶仪",
    "note": ""
  },
  {
    "id": "w026",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 13,
    "type": "单词",
    "word": "tourism",
    "phonetic": "/ˈtʊərɪzəm/",
    "partOfSpeech": "n.",
    "meaning": "旅游业；观光业",
    "note": ""
  },
  {
    "id": "w027",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 13,
    "type": "单词",
    "word": "surely",
    "phonetic": "/ˈʃʊəli/",
    "partOfSpeech": "adv.",
    "meaning": "确实地；无疑地",
    "note": ""
  },
  {
    "id": "w028",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 13,
    "type": "单词",
    "word": "provide",
    "phonetic": "/prəˈvaɪd/",
    "partOfSpeech": "v.",
    "meaning": "提供；供应；供给",
    "note": ""
  },
  {
    "id": "w029",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 13,
    "type": "单词",
    "word": "low",
    "phonetic": "/ləʊ/",
    "partOfSpeech": "adj.",
    "meaning": "少的；低的",
    "note": ""
  },
  {
    "id": "w030",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 13,
    "type": "单词",
    "word": "beyond",
    "phonetic": "/bɪˈjɒnd/",
    "partOfSpeech": "adv.",
    "meaning": "在更远处；往更远处",
    "note": ""
  },
  {
    "id": "w031",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 13,
    "type": "单词",
    "word": "virtual",
    "phonetic": "/ˈvɜːtʃuəl/",
    "partOfSpeech": "adj.",
    "meaning": "虚拟的；模拟的",
    "note": ""
  },
  {
    "id": "w032",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 13,
    "type": "单词",
    "word": "reality",
    "phonetic": "/riˈæləti/",
    "partOfSpeech": "n.",
    "meaning": "真实；现实",
    "note": ""
  },
  {
    "id": "w033",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 13,
    "type": "单词",
    "word": "fashionable",
    "phonetic": "/ˈfæʃənəbl/",
    "partOfSpeech": "adj.",
    "meaning": "时髦的；流行的",
    "note": ""
  },
  {
    "id": "w034",
    "imageIndex": 1,
    "unit": "Unit 1",
    "page": 13,
    "type": "单词",
    "word": "market",
    "phonetic": "/ˈmɑːkɪt/",
    "partOfSpeech": "n.",
    "meaning": "市场",
    "note": ""
  },
  {
    "id": "w035",
    "imageIndex": 1,
    "unit": "Unit 2",
    "page": 21,
    "type": "单词",
    "word": "pm",
    "phonetic": "/ˌpiː ˈem/",
    "partOfSpeech": "n.",
    "meaning": "下午；午后",
    "note": "用于表示钟点数字之后"
  },
  {
    "id": "w036",
    "imageIndex": 1,
    "unit": "Unit 2",
    "page": 21,
    "type": "单词",
    "word": "promise",
    "phonetic": "/ˈprɒmɪs/",
    "partOfSpeech": "n.; v.",
    "meaning": "保证；承诺；诺言；许诺；答应",
    "note": ""
  },
  {
    "id": "w037",
    "imageIndex": 1,
    "unit": "Unit 2",
    "page": 21,
    "type": "单词",
    "word": "tonight",
    "phonetic": "/təˈnaɪt/",
    "partOfSpeech": "adv.",
    "meaning": "今晚",
    "note": ""
  },
  {
    "id": "w038",
    "imageIndex": 1,
    "unit": "Unit 2",
    "page": 21,
    "type": "单词",
    "word": "interrupt",
    "phonetic": "/ˌɪntəˈrʌpt/",
    "partOfSpeech": "v.",
    "meaning": "打断；中断；打扰",
    "note": ""
  },
  {
    "id": "w039",
    "imageIndex": 1,
    "unit": "Unit 2",
    "page": 21,
    "type": "单词",
    "word": "lamp",
    "phonetic": "/læmp/",
    "partOfSpeech": "n.",
    "meaning": "灯",
    "note": ""
  },
  {
    "id": "w040",
    "imageIndex": 1,
    "unit": "Unit 2",
    "page": 21,
    "type": "单词",
    "word": "blouse",
    "phonetic": "/blaʊz/",
    "partOfSpeech": "n.",
    "meaning": "女士宽松短衫；女衬衫",
    "note": ""
  },
  {
    "id": "w041",
    "imageIndex": 1,
    "unit": "Unit 2",
    "page": 21,
    "type": "单词",
    "word": "pale",
    "phonetic": "/peɪl/",
    "partOfSpeech": "adj.",
    "meaning": "苍白的",
    "note": ""
  },
  {
    "id": "w042",
    "imageIndex": 1,
    "unit": "Unit 2",
    "page": 21,
    "type": "单词",
    "word": "attach",
    "phonetic": "/əˈtætʃ/",
    "partOfSpeech": "v.",
    "meaning": "系；绑；贴",
    "note": ""
  },
  {
    "id": "w043",
    "imageIndex": 1,
    "unit": "Unit 2",
    "page": 21,
    "type": "单词",
    "word": "wrist",
    "phonetic": "/rɪst/",
    "partOfSpeech": "n.",
    "meaning": "腕；腕关节",
    "note": ""
  },
  {
    "id": "w044",
    "imageIndex": 1,
    "unit": "Unit 2",
    "page": 21,
    "type": "单词",
    "word": "policewoman",
    "phonetic": "/pəˈliːsˌwʊmən/",
    "partOfSpeech": "n.",
    "meaning": "女警察",
    "note": ""
  },
  {
    "id": "w045",
    "imageIndex": 1,
    "unit": "Unit 2",
    "page": 22,
    "type": "单词",
    "word": "elderly",
    "phonetic": "/ˈeldəli/",
    "partOfSpeech": "adj.",
    "meaning": "年老的；渐老的",
    "note": "委婉用法"
  },
  {
    "id": "w046",
    "imageIndex": 1,
    "unit": "Unit 2",
    "page": 22,
    "type": "单词",
    "word": "plot",
    "phonetic": "/plɒt/",
    "partOfSpeech": "n.",
    "meaning": "情节",
    "note": ""
  },
  {
    "id": "w047",
    "imageIndex": 1,
    "unit": "Unit 2",
    "page": 22,
    "type": "单词",
    "word": "point",
    "phonetic": "/pɔɪnt/",
    "partOfSpeech": "n.",
    "meaning": "要点；重点；中心意思；主要含义；观点",
    "note": ""
  },
  {
    "id": "w048",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 23,
    "type": "单词",
    "word": "lazy",
    "phonetic": "/ˈleɪzi/",
    "partOfSpeech": "adj.",
    "meaning": "懒洋洋的；懒惰的",
    "note": ""
  },
  {
    "id": "w049",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 23,
    "type": "单词",
    "word": "sofa",
    "phonetic": "/ˈsəʊfə/",
    "partOfSpeech": "n.",
    "meaning": "长沙发",
    "note": ""
  },
  {
    "id": "w050",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 23,
    "type": "单词",
    "word": "term",
    "phonetic": "/tɜːm/",
    "partOfSpeech": "n.",
    "meaning": "学期",
    "note": ""
  },
  {
    "id": "w051",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 23,
    "type": "单词",
    "word": "spend",
    "phonetic": "/spend/",
    "partOfSpeech": "v.",
    "meaning": "花（时间）",
    "note": ""
  },
  {
    "id": "w052",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 23,
    "type": "单词",
    "word": "conversation",
    "phonetic": "/ˌkɒnvəˈseɪʃən/",
    "partOfSpeech": "n.",
    "meaning": "谈话；交谈；会话",
    "note": ""
  },
  {
    "id": "w053",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 24,
    "type": "单词",
    "word": "disagreement",
    "phonetic": "/ˌdɪsəˈɡriːmənt/",
    "partOfSpeech": "n.",
    "meaning": "意见不合；分歧；争论",
    "note": ""
  },
  {
    "id": "w054",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 25,
    "type": "单词",
    "word": "attitude",
    "phonetic": "/ˈætɪtjuːd/",
    "partOfSpeech": "n.",
    "meaning": "看法；态度",
    "note": ""
  },
  {
    "id": "w055",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 27,
    "type": "单词",
    "word": "childhood",
    "phonetic": "/ˈtʃaɪldhʊd/",
    "partOfSpeech": "n.",
    "meaning": "童年；儿童时代",
    "note": ""
  },
  {
    "id": "w056",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 27,
    "type": "单词",
    "word": "peer",
    "phonetic": "/pɪə/",
    "partOfSpeech": "n.",
    "meaning": "同龄人",
    "note": ""
  },
  {
    "id": "w057",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 27,
    "type": "单词",
    "word": "pressure",
    "phonetic": "/ˈpreʃə/",
    "partOfSpeech": "n.",
    "meaning": "压力",
    "note": "工作或生活中的压力"
  },
  {
    "id": "w058",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 29,
    "type": "单词",
    "word": "disappointed",
    "phonetic": "/ˌdɪsəˈpɔɪntɪd/",
    "partOfSpeech": "adj.",
    "meaning": "失望的；沮丧的",
    "note": ""
  },
  {
    "id": "w059",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 29,
    "type": "单词",
    "word": "fail",
    "phonetic": "/feɪl/",
    "partOfSpeech": "v.",
    "meaning": "失败；未做到",
    "note": ""
  },
  {
    "id": "w060",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 29,
    "type": "单词",
    "word": "heartbreaking",
    "phonetic": "/ˈhɑːtˌbreɪkɪŋ/",
    "partOfSpeech": "adj.",
    "meaning": "使人心碎的",
    "note": ""
  },
  {
    "id": "w061",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 29,
    "type": "单词",
    "word": "skiing",
    "phonetic": "/ˈskiːɪŋ/",
    "partOfSpeech": "n.",
    "meaning": "滑雪运动",
    "note": ""
  },
  {
    "id": "w062",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 29,
    "type": "单词",
    "word": "completely",
    "phonetic": "/kəmˈpliːtli/",
    "partOfSpeech": "adv.",
    "meaning": "完全地；全部地；彻底地",
    "note": ""
  },
  {
    "id": "w063",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 29,
    "type": "单词",
    "word": "upon",
    "phonetic": "/əˈpɒn/",
    "partOfSpeech": "prep.",
    "meaning": "在……上面",
    "note": ""
  },
  {
    "id": "w064",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 29,
    "type": "表达",
    "word": "fall upon",
    "phonetic": "",
    "partOfSpeech": "",
    "meaning": "落在（某人）身上",
    "note": ""
  },
  {
    "id": "w065",
    "imageIndex": 2,
    "unit": "Unit 2",
    "page": 29,
    "type": "单词",
    "word": "clearly",
    "phonetic": "/ˈklɪəli/",
    "partOfSpeech": "adv.",
    "meaning": "清楚地；明白地",
    "note": ""
  },
  {
    "id": "w066",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 36,
    "type": "单词",
    "word": "director",
    "phonetic": "/dəˈrektə/",
    "partOfSpeech": "n.",
    "meaning": "导演",
    "note": ""
  },
  {
    "id": "w067",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 36,
    "type": "单词",
    "word": "drama",
    "phonetic": "/ˈdrɑːmə/",
    "partOfSpeech": "n.",
    "meaning": "戏剧",
    "note": ""
  },
  {
    "id": "w068",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 36,
    "type": "单词",
    "word": "leader",
    "phonetic": "/ˈliːdə/",
    "partOfSpeech": "n.",
    "meaning": "领导者",
    "note": ""
  },
  {
    "id": "w069",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 36,
    "type": "单词",
    "word": "role",
    "phonetic": "/rəʊl/",
    "partOfSpeech": "n.",
    "meaning": "角色",
    "note": ""
  },
  {
    "id": "w070",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 36,
    "type": "单词",
    "word": "freeze",
    "phonetic": "/friːz/",
    "partOfSpeech": "v.",
    "meaning": "突然停止；呆住",
    "note": ""
  },
  {
    "id": "w071",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 36,
    "type": "单词",
    "word": "silence",
    "phonetic": "/ˈsaɪləns/",
    "partOfSpeech": "n.",
    "meaning": "沉默；缄默",
    "note": ""
  },
  {
    "id": "w072",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 36,
    "type": "单词",
    "word": "awful",
    "phonetic": "/ˈɔːfəl/",
    "partOfSpeech": "adj.",
    "meaning": "糟糕的；恶劣的",
    "note": ""
  },
  {
    "id": "w073",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 36,
    "type": "单词",
    "word": "advise",
    "phonetic": "/ədˈvaɪz/",
    "partOfSpeech": "v.",
    "meaning": "建议",
    "note": ""
  },
  {
    "id": "w074",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 36,
    "type": "单词",
    "word": "yours",
    "phonetic": "/jɔːz/",
    "partOfSpeech": "pron.",
    "meaning": "你真挚的",
    "note": "用于以头衔加姓氏称呼收信人的信函末尾"
  },
  {
    "id": "w075",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 37,
    "type": "单词",
    "word": "teamwork",
    "phonetic": "/ˈtiːmwɜːk/",
    "partOfSpeech": "n.",
    "meaning": "合作；协作；配合",
    "note": ""
  },
  {
    "id": "w076",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 37,
    "type": "单词",
    "word": "strength",
    "phonetic": "/streŋθ/",
    "partOfSpeech": "n.",
    "meaning": "优点；长处；优势",
    "note": ""
  },
  {
    "id": "w077",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 37,
    "type": "单词",
    "word": "weakness",
    "phonetic": "/ˈwiːknəs/",
    "partOfSpeech": "n.",
    "meaning": "弱点；缺点；不足",
    "note": ""
  },
  {
    "id": "w078",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 37,
    "type": "单词",
    "word": "vote",
    "phonetic": "/vəʊt/",
    "partOfSpeech": "v.",
    "meaning": "投票；表决",
    "note": ""
  },
  {
    "id": "w079",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 38,
    "type": "单词",
    "word": "suggestion",
    "phonetic": "/səˈdʒestʃən/",
    "partOfSpeech": "n.",
    "meaning": "建议；提议",
    "note": ""
  },
  {
    "id": "w080",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 39,
    "type": "单词",
    "word": "meeting",
    "phonetic": "/ˈmiːtɪŋ/",
    "partOfSpeech": "n.",
    "meaning": "会议",
    "note": ""
  },
  {
    "id": "w081",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 39,
    "type": "单词",
    "word": "captain",
    "phonetic": "/ˈkæptɪn/",
    "partOfSpeech": "n.",
    "meaning": "队长；组长",
    "note": ""
  },
  {
    "id": "w082",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 39,
    "type": "单词",
    "word": "shy",
    "phonetic": "/ʃaɪ/",
    "partOfSpeech": "adj.",
    "meaning": "羞怯的；腼腆的",
    "note": "尤指在陌生人面前"
  },
  {
    "id": "w083",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 39,
    "type": "单词",
    "word": "confidence",
    "phonetic": "/ˈkɒnfɪdəns/",
    "partOfSpeech": "n.",
    "meaning": "自信；信心",
    "note": ""
  },
  {
    "id": "w084",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 41,
    "type": "单词",
    "word": "tent",
    "phonetic": "/tent/",
    "partOfSpeech": "n.",
    "meaning": "帐篷",
    "note": ""
  },
  {
    "id": "w085",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 42,
    "type": "单词",
    "word": "camp",
    "phonetic": "/kæmp/",
    "partOfSpeech": "v.",
    "meaning": "扎营；宿营；露营",
    "note": ""
  },
  {
    "id": "w086",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 42,
    "type": "表达",
    "word": "go camping",
    "phonetic": "",
    "partOfSpeech": "",
    "meaning": "去露营",
    "note": "尤指到山上或森林里"
  },
  {
    "id": "w087",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 42,
    "type": "单词",
    "word": "break",
    "phonetic": "/breɪk/",
    "partOfSpeech": "v.",
    "meaning": "使破裂；使破碎",
    "note": ""
  },
  {
    "id": "w088",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 43,
    "type": "单词",
    "word": "tape",
    "phonetic": "/teɪp/",
    "partOfSpeech": "n.",
    "meaning": "胶带；胶布",
    "note": ""
  },
  {
    "id": "w089",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 43,
    "type": "单词",
    "word": "voluntary",
    "phonetic": "/ˈvɒləntəri/",
    "partOfSpeech": "adj.",
    "meaning": "志愿的",
    "note": ""
  },
  {
    "id": "w090",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 43,
    "type": "单词",
    "word": "cooperation",
    "phonetic": "/kəʊˌɒpəˈreɪʃən/",
    "partOfSpeech": "n.",
    "meaning": "合作；协作",
    "note": ""
  },
  {
    "id": "w091",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 44,
    "type": "单词",
    "word": "noon",
    "phonetic": "/nuːn/",
    "partOfSpeech": "n.",
    "meaning": "正午；中午",
    "note": ""
  },
  {
    "id": "w092",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 44,
    "type": "单词",
    "word": "climber",
    "phonetic": "/ˈklaɪmə/",
    "partOfSpeech": "n.",
    "meaning": "登山运动员",
    "note": ""
  },
  {
    "id": "w093",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 44,
    "type": "单词",
    "word": "roof",
    "phonetic": "/ruːf/",
    "partOfSpeech": "n.",
    "meaning": "顶；顶部",
    "note": ""
  },
  {
    "id": "w094",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 44,
    "type": "表达",
    "word": "roof of the world",
    "phonetic": "",
    "partOfSpeech": "",
    "meaning": "世界屋脊",
    "note": ""
  },
  {
    "id": "w095",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 44,
    "type": "单词",
    "word": "ladder",
    "phonetic": "/ˈlædə/",
    "partOfSpeech": "n.",
    "meaning": "梯子",
    "note": ""
  },
  {
    "id": "w096",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 44,
    "type": "单词",
    "word": "teammate",
    "phonetic": "/ˈtiːmmeɪt/",
    "partOfSpeech": "n.",
    "meaning": "队友",
    "note": ""
  },
  {
    "id": "w097",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 44,
    "type": "单词",
    "word": "lower",
    "phonetic": "/ˈləʊə/",
    "partOfSpeech": "v.",
    "meaning": "把（某物）移低；降下",
    "note": ""
  },
  {
    "id": "w098",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 45,
    "type": "单词",
    "word": "painful",
    "phonetic": "/ˈpeɪnfl/",
    "partOfSpeech": "adj.",
    "meaning": "令人痛苦的",
    "note": ""
  },
  {
    "id": "w099",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 45,
    "type": "单词",
    "word": "rope",
    "phonetic": "/rəʊp/",
    "partOfSpeech": "n.",
    "meaning": "绳；粗绳；绳索",
    "note": ""
  },
  {
    "id": "w100",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 45,
    "type": "单词",
    "word": "effort",
    "phonetic": "/ˈefət/",
    "partOfSpeech": "n.",
    "meaning": "努力",
    "note": ""
  },
  {
    "id": "w101",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 45,
    "type": "表达",
    "word": "make every effort",
    "phonetic": "",
    "partOfSpeech": "",
    "meaning": "尽一切努力",
    "note": ""
  },
  {
    "id": "w102",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 45,
    "type": "单词",
    "word": "north",
    "phonetic": "/nɔːθ/",
    "partOfSpeech": "adj.",
    "meaning": "北方的；北部的；朝北的",
    "note": ""
  },
  {
    "id": "w103",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 45,
    "type": "单词",
    "word": "base",
    "phonetic": "/beɪs/",
    "partOfSpeech": "n.",
    "meaning": "基地；根据地；总部；大本营",
    "note": ""
  },
  {
    "id": "w104",
    "imageIndex": 2,
    "unit": "Unit 3",
    "page": 45,
    "type": "表达",
    "word": "base camp",
    "phonetic": "",
    "partOfSpeech": "",
    "meaning": "登山大本营",
    "note": ""
  },
  {
    "id": "w105",
    "imageIndex": 3,
    "unit": "Unit 3",
    "page": 45,
    "type": "单词",
    "word": "mountaineering",
    "phonetic": "/ˌmaʊntəˈnɪərɪŋ/",
    "partOfSpeech": "n.",
    "meaning": "登山运动",
    "note": ""
  },
  {
    "id": "w106",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 52,
    "type": "单词",
    "word": "excuse",
    "phonetic": "/ɪkˈskjuːz/",
    "partOfSpeech": "v.",
    "meaning": "原谅",
    "note": ""
  },
  {
    "id": "w107",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 52,
    "type": "表达",
    "word": "excuse me",
    "phonetic": "",
    "partOfSpeech": "",
    "meaning": "劳驾；用于礼貌地引起他人注意，尤其是发问时",
    "note": ""
  },
  {
    "id": "w108",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 52,
    "type": "单词",
    "word": "purple",
    "phonetic": "/ˈpɜːpl/",
    "partOfSpeech": "adj.",
    "meaning": "紫色的",
    "note": ""
  },
  {
    "id": "w109",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 52,
    "type": "单词",
    "word": "crayon",
    "phonetic": "/ˈkreɪən/",
    "partOfSpeech": "n.",
    "meaning": "彩色蜡笔",
    "note": ""
  },
  {
    "id": "w110",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 52,
    "type": "单词",
    "word": "sunshine",
    "phonetic": "/ˈsʌnʃaɪn/",
    "partOfSpeech": "n.",
    "meaning": "阳光",
    "note": ""
  },
  {
    "id": "w111",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 52,
    "type": "单词",
    "word": "virus",
    "phonetic": "/ˈvaɪrəs/",
    "partOfSpeech": "n.",
    "meaning": "病毒",
    "note": ""
  },
  {
    "id": "w112",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 52,
    "type": "单词",
    "word": "afford",
    "phonetic": "/əˈfɔːd/",
    "partOfSpeech": "v.",
    "meaning": "买得起",
    "note": ""
  },
  {
    "id": "w113",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 52,
    "type": "单词",
    "word": "disappointment",
    "phonetic": "/ˌdɪsəˈpɔɪntmənt/",
    "partOfSpeech": "n.",
    "meaning": "失望；扫兴；沮丧",
    "note": ""
  },
  {
    "id": "w114",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 53,
    "type": "单词",
    "word": "X-ray",
    "phonetic": "/ˈeks reɪ/",
    "partOfSpeech": "n.",
    "meaning": "X光检查",
    "note": ""
  },
  {
    "id": "w115",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 53,
    "type": "单词",
    "word": "treatment",
    "phonetic": "/ˈtriːtmənt/",
    "partOfSpeech": "n.",
    "meaning": "治疗；诊治；疗法",
    "note": ""
  },
  {
    "id": "w116",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 53,
    "type": "单词",
    "word": "pocket",
    "phonetic": "/ˈpɒkɪt/",
    "partOfSpeech": "n.",
    "meaning": "衣袋；口袋",
    "note": ""
  },
  {
    "id": "w117",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 53,
    "type": "表达",
    "word": "pocket money",
    "phonetic": "",
    "partOfSpeech": "",
    "meaning": "零花钱",
    "note": ""
  },
  {
    "id": "w118",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 53,
    "type": "单词",
    "word": "illness",
    "phonetic": "/ˈɪlnəs/",
    "partOfSpeech": "n.",
    "meaning": "病；疾病；患病状态",
    "note": ""
  },
  {
    "id": "w119",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 53,
    "type": "单词",
    "word": "wheelchair",
    "phonetic": "/ˈwiːltʃeə/",
    "partOfSpeech": "n.",
    "meaning": "轮椅",
    "note": ""
  },
  {
    "id": "w120",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 53,
    "type": "单词",
    "word": "public",
    "phonetic": "/ˈpʌblɪk/",
    "partOfSpeech": "adj.",
    "meaning": "公开的",
    "note": ""
  },
  {
    "id": "w121",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 53,
    "type": "表达",
    "word": "go public",
    "phonetic": "",
    "partOfSpeech": "",
    "meaning": "公开；公之于众",
    "note": ""
  },
  {
    "id": "w122",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 54,
    "type": "单词",
    "word": "mention",
    "phonetic": "/ˈmenʃən/",
    "partOfSpeech": "v.",
    "meaning": "提到；说起；谈到",
    "note": ""
  },
  {
    "id": "w123",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 54,
    "type": "单词",
    "word": "directly",
    "phonetic": "/dəˈrektli/",
    "partOfSpeech": "adv.",
    "meaning": "坦率地；直截了当地",
    "note": ""
  },
  {
    "id": "w124",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 54,
    "type": "单词",
    "word": "solution",
    "phonetic": "/səˈluːʃən/",
    "partOfSpeech": "n.",
    "meaning": "解决方法",
    "note": ""
  },
  {
    "id": "w125",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 55,
    "type": "单词",
    "word": "bottle",
    "phonetic": "/ˈbɒtl/",
    "partOfSpeech": "n.",
    "meaning": "瓶子",
    "note": ""
  },
  {
    "id": "w126",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 55,
    "type": "表达",
    "word": "a bottle of",
    "phonetic": "",
    "partOfSpeech": "",
    "meaning": "一瓶",
    "note": ""
  },
  {
    "id": "w127",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 55,
    "type": "单词",
    "word": "exam",
    "phonetic": "/ɪɡˈzæm/",
    "partOfSpeech": "n.",
    "meaning": "考试",
    "note": ""
  },
  {
    "id": "w128",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 55,
    "type": "单词",
    "word": "dialogue",
    "phonetic": "/ˈdaɪəlɒɡ/",
    "partOfSpeech": "n.",
    "meaning": "对话",
    "note": ""
  },
  {
    "id": "w129",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 55,
    "type": "单词",
    "word": "flu",
    "phonetic": "/fluː/",
    "partOfSpeech": "n.",
    "meaning": "流行性感冒；流感",
    "note": ""
  },
  {
    "id": "w130",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 58,
    "type": "单词",
    "word": "homeless",
    "phonetic": "/ˈhəʊmləs/",
    "partOfSpeech": "adj.",
    "meaning": "无家可归的",
    "note": ""
  },
  {
    "id": "w131",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 58,
    "type": "单词",
    "word": "donate",
    "phonetic": "/dəʊˈneɪt/",
    "partOfSpeech": "v.",
    "meaning": "捐赠；捐献",
    "note": ""
  },
  {
    "id": "w132",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 60,
    "type": "单词",
    "word": "soldier",
    "phonetic": "/ˈsəʊldʒə/",
    "partOfSpeech": "n.",
    "meaning": "士兵；军人",
    "note": ""
  },
  {
    "id": "w133",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 60,
    "type": "单词",
    "word": "fireman",
    "phonetic": "/ˈfaɪəmən/",
    "partOfSpeech": "n.",
    "meaning": "消防队员",
    "note": ""
  },
  {
    "id": "w134",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 60,
    "type": "单词",
    "word": "against",
    "phonetic": "/əˈɡenst/",
    "partOfSpeech": "prep.",
    "meaning": "和……对抗",
    "note": ""
  },
  {
    "id": "w135",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 60,
    "type": "单词",
    "word": "graduate",
    "phonetic": "/ˈɡrædʒueɪt/",
    "partOfSpeech": "v.",
    "meaning": "大学毕业",
    "note": ""
  },
  {
    "id": "w136",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 60,
    "type": "单词",
    "word": "college",
    "phonetic": "/ˈkɒlɪdʒ/",
    "partOfSpeech": "n.",
    "meaning": "大学；学院",
    "note": ""
  },
  {
    "id": "w137",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 61,
    "type": "单词",
    "word": "warmth",
    "phonetic": "/wɔːmθ/",
    "partOfSpeech": "n.",
    "meaning": "温暖",
    "note": ""
  },
  {
    "id": "w138",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 61,
    "type": "单词",
    "word": "means",
    "phonetic": "/miːnz/",
    "partOfSpeech": "n.",
    "meaning": "手段；方法；工具",
    "note": ""
  },
  {
    "id": "w139",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 61,
    "type": "表达",
    "word": "by no means",
    "phonetic": "",
    "partOfSpeech": "",
    "meaning": "绝不；一点儿都不",
    "note": ""
  },
  {
    "id": "w140",
    "imageIndex": 3,
    "unit": "Unit 4",
    "page": 61,
    "type": "单词",
    "word": "lucky",
    "phonetic": "/ˈlʌki/",
    "partOfSpeech": "adj.",
    "meaning": "运气好的；幸运的",
    "note": ""
  },
  {
    "id": "w141",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 68,
    "type": "单词",
    "word": "dinosaur",
    "phonetic": "/ˈdaɪnəsɔː/",
    "partOfSpeech": "n.",
    "meaning": "恐龙",
    "note": ""
  },
  {
    "id": "w142",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 68,
    "type": "单词",
    "word": "feather",
    "phonetic": "/ˈfeðə/",
    "partOfSpeech": "n.",
    "meaning": "羽毛；翎",
    "note": ""
  },
  {
    "id": "w143",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 68,
    "type": "单词",
    "word": "feather-covered",
    "phonetic": "/ˈfeðə ˌkʌvəd/",
    "partOfSpeech": "adj.",
    "meaning": "羽毛覆盖的",
    "note": ""
  },
  {
    "id": "w144",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 68,
    "type": "单词",
    "word": "lizard",
    "phonetic": "/ˈlɪzəd/",
    "partOfSpeech": "n.",
    "meaning": "蜥蜴",
    "note": ""
  },
  {
    "id": "w145",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 68,
    "type": "单词",
    "word": "amber",
    "phonetic": "/ˈæmbə/",
    "partOfSpeech": "n.",
    "meaning": "琥珀",
    "note": ""
  },
  {
    "id": "w146",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 69,
    "type": "单词",
    "word": "whether",
    "phonetic": "/ˈweðə/",
    "partOfSpeech": "conj.",
    "meaning": "是否",
    "note": "用于表示选择或对某事不确定"
  },
  {
    "id": "w147",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 69,
    "type": "单词",
    "word": "northern",
    "phonetic": "/ˈnɔːðən/",
    "partOfSpeech": "adj.",
    "meaning": "北部的",
    "note": ""
  },
  {
    "id": "w148",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 69,
    "type": "单词",
    "word": "species",
    "phonetic": "/ˈspiːʃiːz/",
    "partOfSpeech": "n.",
    "meaning": "物种",
    "note": ""
  },
  {
    "id": "w149",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 69,
    "type": "单词",
    "word": "unknown",
    "phonetic": "/ˌʌnˈnəʊn/",
    "partOfSpeech": "adj.",
    "meaning": "不知道的；未知的",
    "note": ""
  },
  {
    "id": "w150",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 69,
    "type": "单词",
    "word": "African",
    "phonetic": "/ˈæfrɪkən/",
    "partOfSpeech": "adj.",
    "meaning": "非洲的；非洲人的",
    "note": ""
  },
  {
    "id": "w151",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 69,
    "type": "单词",
    "word": "belief",
    "phonetic": "/bɪˈliːf/",
    "partOfSpeech": "n.",
    "meaning": "观点",
    "note": ""
  },
  {
    "id": "w152",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 69,
    "type": "单词",
    "word": "fully",
    "phonetic": "/ˈfʊli/",
    "partOfSpeech": "adv.",
    "meaning": "完全地；充分地；彻底地",
    "note": ""
  },
  {
    "id": "w153",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 69,
    "type": "单词",
    "word": "unlock",
    "phonetic": "/ˌʌnˈlɒk/",
    "partOfSpeech": "v.",
    "meaning": "揭开",
    "note": ""
  },
  {
    "id": "w154",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 69,
    "type": "表达",
    "word": "unlock the secrets of sth",
    "phonetic": "",
    "partOfSpeech": "",
    "meaning": "揭开某事的秘密",
    "note": ""
  },
  {
    "id": "w155",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 70,
    "type": "单词",
    "word": "newspaper",
    "phonetic": "/ˈnjuːzˌpeɪpə/",
    "partOfSpeech": "n.",
    "meaning": "报纸",
    "note": ""
  },
  {
    "id": "w156",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 70,
    "type": "单词",
    "word": "writing",
    "phonetic": "/ˈraɪtɪŋ/",
    "partOfSpeech": "n.",
    "meaning": "写作；著书",
    "note": ""
  },
  {
    "id": "w157",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 70,
    "type": "单词",
    "word": "style",
    "phonetic": "/staɪl/",
    "partOfSpeech": "n.",
    "meaning": "风格",
    "note": ""
  },
  {
    "id": "w158",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 70,
    "type": "单词",
    "word": "method",
    "phonetic": "/ˈmeθəd/",
    "partOfSpeech": "n.",
    "meaning": "方法；办法",
    "note": ""
  },
  {
    "id": "w159",
    "imageIndex": 3,
    "unit": "Unit 5",
    "page": 70,
    "type": "单词",
    "word": "text",
    "phonetic": "/tekst/",
    "partOfSpeech": "n.",
    "meaning": "文字材料",
    "note": ""
  },
  {
    "id": "w160",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 70,
    "type": "单词",
    "word": "alive",
    "phonetic": "/əˈlaɪv/",
    "partOfSpeech": "adj.",
    "meaning": "有活力的；有生气的",
    "note": ""
  },
  {
    "id": "w161",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 70,
    "type": "单词",
    "word": "argument",
    "phonetic": "/ˈɑːɡjəmənt/",
    "partOfSpeech": "n.",
    "meaning": "论点；论据",
    "note": ""
  },
  {
    "id": "w162",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 71,
    "type": "单词",
    "word": "board",
    "phonetic": "/bɔːd/",
    "partOfSpeech": "n.",
    "meaning": "布告牌；公告牌",
    "note": ""
  },
  {
    "id": "w163",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 71,
    "type": "单词",
    "word": "model",
    "phonetic": "/ˈmɒdl/",
    "partOfSpeech": "n.",
    "meaning": "模型",
    "note": ""
  },
  {
    "id": "w164",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 71,
    "type": "单词",
    "word": "planet",
    "phonetic": "/ˈplænɪt/",
    "partOfSpeech": "n.",
    "meaning": "行星",
    "note": ""
  },
  {
    "id": "w165",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 71,
    "type": "单词",
    "word": "clear",
    "phonetic": "/klɪə/",
    "partOfSpeech": "v.",
    "meaning": "清除；清理",
    "note": ""
  },
  {
    "id": "w166",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 72,
    "type": "单词",
    "word": "upload",
    "phonetic": "/ˌʌpˈləʊd/",
    "partOfSpeech": "v.",
    "meaning": "上载；上传",
    "note": ""
  },
  {
    "id": "w167",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 72,
    "type": "单词",
    "word": "whale",
    "phonetic": "/weɪl/",
    "partOfSpeech": "n.",
    "meaning": "鲸",
    "note": ""
  },
  {
    "id": "w168",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 73,
    "type": "单词",
    "word": "boiling",
    "phonetic": "/ˈbɔɪlɪŋ/",
    "partOfSpeech": "adj.",
    "meaning": "很热的；滚烫的",
    "note": ""
  },
  {
    "id": "w169",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 75,
    "type": "单词",
    "word": "chemical",
    "phonetic": "/ˈkemɪkl/",
    "partOfSpeech": "n.",
    "meaning": "化学品",
    "note": ""
  },
  {
    "id": "w170",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 76,
    "type": "单词",
    "word": "endless",
    "phonetic": "/ˈendləs/",
    "partOfSpeech": "adj.",
    "meaning": "无数的；无限的",
    "note": ""
  },
  {
    "id": "w171",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 76,
    "type": "单词",
    "word": "sight",
    "phonetic": "/saɪt/",
    "partOfSpeech": "n.",
    "meaning": "视力；视觉",
    "note": ""
  },
  {
    "id": "w172",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 76,
    "type": "单词",
    "word": "anybody",
    "phonetic": "/ˈeniˌbɒdi/",
    "partOfSpeech": "pron.",
    "meaning": "任何人",
    "note": ""
  },
  {
    "id": "w173",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 76,
    "type": "单词",
    "word": "magnifier",
    "phonetic": "/ˈmæɡnɪfaɪə/",
    "partOfSpeech": "n.",
    "meaning": "放大镜",
    "note": ""
  },
  {
    "id": "w174",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 77,
    "type": "单词",
    "word": "wealth",
    "phonetic": "/welθ/",
    "partOfSpeech": "n.",
    "meaning": "财富",
    "note": ""
  },
  {
    "id": "w175",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 77,
    "type": "单词",
    "word": "hardly",
    "phonetic": "/ˈhɑːdli/",
    "partOfSpeech": "adv.",
    "meaning": "几乎不",
    "note": ""
  },
  {
    "id": "w176",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 77,
    "type": "单词",
    "word": "belong",
    "phonetic": "/bɪˈlɒŋ/",
    "partOfSpeech": "v.",
    "meaning": "应在某处",
    "note": ""
  },
  {
    "id": "w177",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 77,
    "type": "表达",
    "word": "belong to",
    "phonetic": "",
    "partOfSpeech": "",
    "meaning": "属于",
    "note": ""
  },
  {
    "id": "w178",
    "imageIndex": 4,
    "unit": "Unit 5",
    "page": 77,
    "type": "单词",
    "word": "granddaughter",
    "phonetic": "/ˈɡrænˌdɔːtə/",
    "partOfSpeech": "n.",
    "meaning": "孙女；外孙女",
    "note": ""
  },
  {
    "id": "w179",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 85,
    "type": "单词",
    "word": "sweetly",
    "phonetic": "/ˈswiːtli/",
    "partOfSpeech": "adv.",
    "meaning": "悦耳动听地；好听地",
    "note": ""
  },
  {
    "id": "w180",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 85,
    "type": "单词",
    "word": "villager",
    "phonetic": "/ˈvɪlɪdʒə/",
    "partOfSpeech": "n.",
    "meaning": "村民",
    "note": ""
  },
  {
    "id": "w181",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 85,
    "type": "单词",
    "word": "wheat",
    "phonetic": "/wiːt/",
    "partOfSpeech": "n.",
    "meaning": "小麦",
    "note": ""
  },
  {
    "id": "w182",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 85,
    "type": "单词",
    "word": "countryside",
    "phonetic": "/ˈkʌntrisaɪd/",
    "partOfSpeech": "n.",
    "meaning": "乡下；农村",
    "note": ""
  },
  {
    "id": "w183",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 85,
    "type": "单词",
    "word": "province",
    "phonetic": "/ˈprɒvɪns/",
    "partOfSpeech": "n.",
    "meaning": "省",
    "note": ""
  },
  {
    "id": "w184",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 85,
    "type": "单词",
    "word": "react",
    "phonetic": "/riˈækt/",
    "partOfSpeech": "v.",
    "meaning": "作出反应",
    "note": ""
  },
  {
    "id": "w185",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 85,
    "type": "单词",
    "word": "especially",
    "phonetic": "/ɪˈspeʃəli/",
    "partOfSpeech": "adv.",
    "meaning": "尤其",
    "note": ""
  },
  {
    "id": "w186",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 85,
    "type": "单词",
    "word": "wisdom",
    "phonetic": "/ˈwɪzdəm/",
    "partOfSpeech": "n.",
    "meaning": "智慧；才智",
    "note": ""
  },
  {
    "id": "w187",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 85,
    "type": "单词",
    "word": "below",
    "phonetic": "/bɪˈləʊ/",
    "partOfSpeech": "prep.",
    "meaning": "在……的下面",
    "note": ""
  },
  {
    "id": "w188",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 85,
    "type": "单词",
    "word": "arrival",
    "phonetic": "/əˈraɪvl/",
    "partOfSpeech": "n.",
    "meaning": "到来",
    "note": ""
  },
  {
    "id": "w189",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 85,
    "type": "单词",
    "word": "calendar",
    "phonetic": "/ˈkælɪndə/",
    "partOfSpeech": "n.",
    "meaning": "历法",
    "note": ""
  },
  {
    "id": "w190",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 87,
    "type": "单词",
    "word": "energetic",
    "phonetic": "/ˌenəˈdʒetɪk/",
    "partOfSpeech": "adj.",
    "meaning": "精力充沛的；充满活力的",
    "note": ""
  },
  {
    "id": "w191",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 88,
    "type": "单词",
    "word": "beekeeping",
    "phonetic": "/ˈbiːˌkiːpɪŋ/",
    "partOfSpeech": "n.",
    "meaning": "养蜂业",
    "note": ""
  },
  {
    "id": "w192",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 88,
    "type": "表达",
    "word": "according to",
    "phonetic": "",
    "partOfSpeech": "",
    "meaning": "据……所示；按……所说",
    "note": ""
  },
  {
    "id": "w193",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 89,
    "type": "单词",
    "word": "desert",
    "phonetic": "/ˈdezət/",
    "partOfSpeech": "n.",
    "meaning": "沙漠；荒漠",
    "note": ""
  },
  {
    "id": "w194",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 89,
    "type": "单词",
    "word": "energy",
    "phonetic": "/ˈenədʒi/",
    "partOfSpeech": "n.",
    "meaning": "能源",
    "note": ""
  },
  {
    "id": "w195",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 89,
    "type": "单词",
    "word": "charge",
    "phonetic": "/tʃɑːdʒ/",
    "partOfSpeech": "v.",
    "meaning": "使充电",
    "note": ""
  },
  {
    "id": "w196",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 91,
    "type": "单词",
    "word": "environment",
    "phonetic": "/ɪnˈvaɪrənmənt/",
    "partOfSpeech": "n.",
    "meaning": "生态环境",
    "note": ""
  },
  {
    "id": "w197",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 91,
    "type": "单词",
    "word": "resource",
    "phonetic": "/rɪˈzɔːs/",
    "partOfSpeech": "n.",
    "meaning": "资源",
    "note": ""
  },
  {
    "id": "w198",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 91,
    "type": "表达",
    "word": "natural resources",
    "phonetic": "",
    "partOfSpeech": "",
    "meaning": "自然资源",
    "note": ""
  },
  {
    "id": "w199",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 92,
    "type": "单词",
    "word": "probably",
    "phonetic": "/ˈprɒbəbli/",
    "partOfSpeech": "adv.",
    "meaning": "很可能；大概",
    "note": ""
  },
  {
    "id": "w200",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 92,
    "type": "单词",
    "word": "west",
    "phonetic": "/west/",
    "partOfSpeech": "n.",
    "meaning": "西；西面",
    "note": ""
  },
  {
    "id": "w201",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 92,
    "type": "单词",
    "word": "east",
    "phonetic": "/iːst/",
    "partOfSpeech": "n.",
    "meaning": "东部",
    "note": ""
  },
  {
    "id": "w202",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 92,
    "type": "单词",
    "word": "midsummer",
    "phonetic": "/ˌmɪdˈsʌmə/",
    "partOfSpeech": "n.",
    "meaning": "仲夏",
    "note": ""
  },
  {
    "id": "w203",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 92,
    "type": "单词",
    "word": "crazy",
    "phonetic": "/ˈkreɪzi/",
    "partOfSpeech": "adj.",
    "meaning": "疯狂的",
    "note": ""
  },
  {
    "id": "w204",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 92,
    "type": "单词",
    "word": "rainfall",
    "phonetic": "/ˈreɪnfɔːl/",
    "partOfSpeech": "n.",
    "meaning": "雨量",
    "note": ""
  },
  {
    "id": "w205",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 92,
    "type": "单词",
    "word": "survive",
    "phonetic": "/səˈvaɪv/",
    "partOfSpeech": "v.",
    "meaning": "活下来；幸存",
    "note": ""
  },
  {
    "id": "w206",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 93,
    "type": "单词",
    "word": "underground",
    "phonetic": "/ˈʌndəɡraʊnd/",
    "partOfSpeech": "adj.",
    "meaning": "地面下的；地下的",
    "note": ""
  },
  {
    "id": "w207",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 93,
    "type": "单词",
    "word": "canal",
    "phonetic": "/kəˈnæl/",
    "partOfSpeech": "n.",
    "meaning": "水渠；沟渠；运河",
    "note": ""
  },
  {
    "id": "w208",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 93,
    "type": "单词",
    "word": "among",
    "phonetic": "/əˈmʌŋ/",
    "partOfSpeech": "prep.",
    "meaning": "是……之一",
    "note": ""
  },
  {
    "id": "w209",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 93,
    "type": "单词",
    "word": "shortage",
    "phonetic": "/ˈʃɔːtɪdʒ/",
    "partOfSpeech": "n.",
    "meaning": "短缺；不足；缺乏",
    "note": ""
  },
  {
    "id": "w210",
    "imageIndex": 4,
    "unit": "Unit 6",
    "page": 93,
    "type": "单词",
    "word": "increase",
    "phonetic": "/ɪnˈkriːs/",
    "partOfSpeech": "n.; v.",
    "meaning": "增加；增多；增长",
    "note": ""
  }
];
